- PRIVACY.md
- README.md
- src/lib/components/chat/ChatIntroduction.svelte
> Release as a GitHub repo

- src/lib/server/database.ts
> 🧑‍💻 Explicit error message when MongoDB configuration lacking

- src/lib/components/chat/ChatMessage.svelte
> Break long word in user message

- src/lib/components/chat/ChatMessage.svelte
Same as #209, but for assistant messages.
> Fix long word in assistant message

- src/lib/components/chat/ChatInput.svelte
> Fix chat input

- package-lock.json
- package.json
- src/lib/components/StopGeneratingBtn.svelte
- src/lib/components/chat/ChatWindow.svelte
The current behavior overlays user input, so I think making it similar to chatGPT would be better.
New in desktop
New in mobile
> Fix stop generating button

- .env
- src/lib/server/database.ts
This is useful with localhost DBs
> 🔧 Add "directConnection" option to MongoDB

- src/routes/+layout.svelte
- src/routes/login/callback/+page.server.ts
As per spec, instead of redirecting to /
> 🥅 Display OIDC error properly

- src/routes/admin/export/+server.ts
Follow-up to #151 to account for #152
> Export to parquet: also export score

- .dockerignore
- Dockerfile
Reduce the docker layer size + enable incremental builds
PS: This `--mount=type=secret,id=DOTENV_LOCAL,dst=.env.local` fell old, we should not need secret at build time.
> Add incremental build + multi layer docker for size reduction

- src/lib/components/OpenWebSearchResults.svelte
- src/routes/+error.svelte
> Safari: fix details arrow

- src/lib/types/Settings.ts
> Fix typo in Settings.ts

- .env
- README.md
**📝  Summary:**
Information about adding endpoints to .env.local was removed in Pull request #264 - Added a few sections to the readme and reorganized it
**⚠️ Related Issue(s):**
#273 - Documentation about how to configure custom model endpoints is missing
**🔍 Code Change:**
[.env](https://github.com/huggingface/chat-ui/compare/main...averad:chat-ui:main#diff-e9cbb0224c4a3d23a6019ba557e0cd568c1ad5e1582ff1e335fb7d99b7a1055d)
`# "endpoints": [{"url": "http://127.0.0.1:8080/generate_stream"}],`
[README.md](https://github.com/huggingface/chat-ui/compare/main...averad:chat-ui:main#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)
` "endpoints": [{"url": "http://127.0.0.1:8080/generate_stream"}],`
> ➕ Update README.md to Include endpoints Variable

- src/lib/types/MessageEvent.ts
- src/routes/conversation/[id]/+server.ts
This PR adds rate limiting based on client IP in cases where the user is not logged in. 
This is a prerequisite to allowing the first message to be sent without logging in.
> Support rate limit based on user IP

- README.md
* ToC link is currently broken
* Move up the Spaces option as a fast deploy option
> Fix ToC + move up space template

- PRIVACY.md
- README.md
- src/lib/components/SettingsModal.svelte
> Update /privacy and other content following Llama v2 release

- src/lib/components/Modal.svelte
- src/lib/components/ModelCardMetadata.svelte
- src/lib/components/ModelsModal.svelte
close #447
https://github.com/huggingface/chat-ui/assets/3841370/5c8a1fde-34d3-43f4-a051-81836a7ae07b
> Mobile: fix model selection

- src/lib/server/websearch/runWebSearch.ts
- src/lib/server/websearch/sentenceSimilarity.ts
Make embedding model settings more future-proof
> Make embedding model settings more future-proof

- src/routes/+layout.svelte
- static/chatui/manifest.json
- static/huggingchat/manifest.json
> Add manifest.json

- PRIVACY.md
- README.md
* Update model list in PRIVACY.md
* Remove mentions of open assistant data sharing
* Fix linting warnings in readme.md
> Privacy update & readme linting

- .env
- README.md
- src/lib/server/auth.ts
> Feature/add OIDC optional tolerance and resource

- .env.template
To test locally:
1. Pull this branch
2. Run `npm run updateLocalEnv`
3. Start your server as usual `npm run dev`
> Add zephyr to config

- src/lib/server/websearch/runWebSearch.ts
Fixes a bug where at the beginning of the model answer it seems to show 1 source and all other sources appear at the end of the answer
> [Websearch] UI fix sources

- src/lib/components/SettingsModal.svelte
- src/lib/types/Settings.ts
- src/routes/+layout.server.ts
- src/routes/settings/+page.server.ts
https://github.com/huggingface/chat-ui/assets/25119303/98d15803-a37b-48e7-a539-90ace6ffccee
> Add checkbox for displaying emojis in sidebar

- README.md
> [DOCS] Minor fixes in README.md

- .github/workflows/lint-and-test.yml
- .gitignore
- Dockerfile
- conf/.env.ci
In order to avoid breaking prod if the dockerfile doesn't build, we can now catch it in PRs
> Add a CI check for dockerfile build

- src/lib/components/DisclaimerModal.svelte
- src/lib/utils/cookiesAreEnabled.ts
> Open in new tab if cookies are disabled

- src/routes/conversation/+server.ts
Hello,
I've created this PR to fix a bug which prevents the preprompt from being sent to the model.
The bug is described in detail in issue https://github.com/huggingface/chat-ui/issues/589.
Please let me know what you think, and if I am missing something.
Suggestions are welcome.
>  Fix conversation preprompt

- src/routes/settings/+page.svelte
> Conditionally show the data sharing toggle

- .env.template
- src/lib/server/models.ts
- src/lib/types/Model.ts
- src/routes/+layout.server.ts
- src/routes/conversation/+server.ts
- src/routes/settings/+layout.svelte
- src/routes/settings/+page.svelte
- src/routes/settings/[...model]/+page.ts
This PR adds mistral 7b v0.2 as an option in HuggingChat, and unlists the v0.1 so we need to merge #625 before.
> Add mistral 7b v0.2

- README.md
I copied the MODELS env and it did not work, so I modified the README.
> Fix MODELS env

- .env.template
Don't merge until https://github.com/huggingface/api-inference/pull/1750 is through
> Use the new openchat model

- .env.template
This change will only apply to new users, as existing users will keep their currently active model.
> Make mixtral the default model for new users

- .env.template
Not a lot of traffic, a lot of GPUs
> Remove falcon 180B

- src/lib/stores/settings.ts
- src/routes/+layout.server.ts
Emojis would show until page refresh despite changing the settings. this PR fixes that
> Apply settings without reloading the page 

- README.md
This has been working for a while but wasn't properly documented, now we have it in the docs!
> Add doc section about updating HuggingChat

- .env
- .env.template
- src/hooks.server.ts
- src/routes/api/available_models/+server.ts
- src/routes/api/conversations/+server.ts
- src/routes/api/models/+server.ts
Hello,
This is the first PR to add endpoints for the upcomming mobile app.
This one expose the json list of available models.
Edit:
I added another endpoint to list conversations history for the current user.
> Add an endpoints to expose models and conversations

- src/routes/api/conversation/[id]/+server.ts
- src/routes/api/conversations/+server.ts
- Sorting conversations for the `/api/conversation` endpoint
- Addind `/api/conversation/[id]` endpoint to get one conversation from its `id`
> Add conversation API endpoint to get conversation

- src/lib/server/generateFromDefaultEndpoint.ts
Reverts huggingface/chat-ui#704
#704 was unnecessary, didn't fix the problem
> Revert "[Small model] Explicitly close AsyncGenerator"

- .env.template
Lower temp config specifically for tasks
> Bring back mistral task model

- src/lib/server/models.ts
Nit: just updating the comment to make it more clear
> [SmallModel] Nit update the comment

- src/lib/server/websearch/generateQuery.ts
small fixes in websearch generateQuery found while digging deeper
> [Fix] small fixes in websearch generateQuery

- .env.template
According to my experiments https://github.com/huggingface/chat-ui-experiments/tree/main/1-task-model-hallucination
> [SmallModel] TASK_MODEL='mistralai/Mistral-7B-Instruct-v0.1'

- README.md
See [internal thread](https://huggingface.slack.com/archives/C02136Y252P/p1706115793253869)
> Add failure strategy to README.md

- .env.template
- PROMPTS.md
Bring back EOS token if no preprompt set
See [internal discussion](https://huggingface.slack.com/archives/C052EKHD1U0/p1706029938469679?thread_ts=1706027093.147679&cid=C052EKHD1U0)
> Update nous prompt

- README.md
> [Fix README] Nit: some small indent issues

- .env
- src/lib/components/chat/ChatIntroduction.svelte
> Update news for code llama

- src/lib/components/chat/ChatMessage.svelte
This just replaces the small avatar on the side of assistant messages
> Use assistant avatar in conversation, if available

- src/routes/conversation/[id]/+page.svelte
- src/routes/conversation/[id]/+server.ts
This makes sure the websearch feature is always disabled on assistants
> Disable websearch on assistants, server & client side

- src/lib/components/chat/ChatInput.svelte
Closes https://github.com/huggingface/chat-ui/issues/403
Read more [here](https://developer.mozilla.org/en-US/docs/Web/API/Element/compositionstart_event)
https://github.com/huggingface/chat-ui/assets/11827707/c8ba2886-b082-4466-864f-d8a4fa9eec15
> [Chat input] Fix asian keyboards

- .env
- scripts/updateProdEnv.ts
- src/routes/settings/assistants/[assistantId]/+page.server.ts
Post to webhook url "report assistant" events
> [Assistnats] improve reporting

- .github/workflows/deploy-release.yml
Follow up to https://github.com/huggingface/chat-ui/pull/797
> Add missing prod config for report assistants

- src/lib/components/chat/ChatInput.svelte
> [Chat input] Blur on submit

- src/routes/assistants/+page.server.ts
- src/routes/assistants/+page.svelte
1. c88931ec87e81d638afa3be692c79eface661482 revert [this commit](https://github.com/huggingface/chat-ui/pull/773#issuecomment-1933753609)
2. f46d458e0afc0e0c159147659434bab83d7d8331 changes the logic to:
1. Remove the featured flag if the user is defined
2. Show 0 user count but only if the logged user is on its profile
3. 458b3936b134a4dc8f41a4d27cba7202ef350403 adds UI hint to Step 2.2 above
> [Assistants] update page & visiblity logic

- src/lib/utils/formatUserCount.ts
- src/routes/assistants/+page.svelte
> /assistants: add user count

- src/lib/utils/formatUserCount.ts
See this comment [here](https://github.com/huggingface/chat-ui/pull/811/files#r1484466583). Suggested by Pierric
> [Assistants] update numbering labels

- src/lib/server/database.ts
- src/routes/settings/assistants/[assistantId]/+page.server.ts
It was running on all users settings which was slow in prod
> Fix delete assistant query performance

- src/routes/settings/assistants/[assistantId]/+page.server.ts
1. Fixes a bug: non-logged in users are being identified as https://huggingface.co/undefined
2. Stronger typing with `Pick` when using mongo projection
> [Assisntats reports] Minor fixes

- src/routes/settings/assistants/[assistantId]/+page.server.ts
- src/routes/settings/assistants/[assistantId]/+page.svelte
- src/routes/settings/assistants/[assistantId]/+page.ts
Reverts huggingface/chat-ui#830 since it broke "Edit" feature. Will re-submit this PR with correct fix
> Revert "[Assistants settings] Fix freezing"

- src/lib/server/database.ts
- src/routes/settings/+layout.server.ts
- src/routes/settings/assistants/[assistantId]/+page.server.ts
As the title says, optimize `reports` collection query
> [Mongo] Optimize `reports` collection query

- src/lib/server/database.ts
- src/routes/settings/+layout.server.ts
- src/routes/settings/assistants/[assistantId]/+page.server.ts
Reverts huggingface/chat-ui#832
> Revert "[Mongo] Optimize `reports` collection query"

- src/lib/server/database.ts
- src/routes/settings/+layout.server.ts
- src/routes/settings/assistants/[assistantId]/+page.server.ts
Same as #832 but needed https://github.com/huggingface/chat-ui/pull/834/commits/e92d06a08503f5bacf3c8ddd81eee9ce6ce56726
> [Mongo] Optimize `reports` collection query (v2)

- src/routes/+layout.server.ts
Perform `count messages` only when necessary
> [Mongo] count messages (aggregate) only when needed

- src/routes/+layout.server.ts
- src/routes/conversation/[id]/+server.ts
fixes #863
needed https://github.com/huggingface/chat-ui/pull/866/commits/9e67e76d75d7257abc5573ae3ec01a8a0040a784
> [Mongo] count messages (aggregate) only when needed V2

- src/routes/conversation/[id]/+page.svelte
There were some issues with invalidating load functions, this should now be fixed.
> Fix Error: Ancestor Not Found issue

- src/routes/assistants/+page.svelte
Should be merged & deployed inly after #897 is deployed. This PR is the last item from [this list](https://github.com/huggingface/chat-ui/pull/841#issuecomment-1979083179)
> [Assistants] Show/enable UI for filtering

- src/routes/assistants/+page.svelte
Previously, assistants filter had `<input disabled={filterIsHappening} />`, which made the UX feel clunky. This PR removes `disabled={filterIsHappening}` from `input` with some logic that can handle queuing as user types while the server had not responded yet to the previous filter query.
> [Assistants filter] Make UI more responsive

- src/lib/components/chat/ChatWindow.svelte
fixes #879 
[Prompt_login.webm](https://github.com/huggingface/chat-ui/assets/94371461/8f881416-e426-4668-8acf-4b9a838f3cda)
> fix: Prompt bypasses login 

- src/lib/server/websearch/runWebSearch.ts
I was missing the boolean operators for google
> Fix multi domains for assistants

- src/lib/types/Conversation.ts
- src/routes/conversation/+server.ts
cc @alak, will this also work on your side ?
> Store user agent in conversation

- src/lib/components/Modal.svelte
- src/routes/settings/+layout.svelte
Avoid wrong modal closing (something we already do on the hub).
> Modals: dont close if text is selected

- src/lib/components/chat/AssistantIntroduction.svelte
Simple feature to share directly from assistant landing page
Closes #960
> Add share button for assistant intro page (#960)

- src/lib/components/chat/AssistantIntroduction.svelte
- src/lib/utils/formatUserCount.ts
> User count update

- .env
- README.md
- package-lock.json
- package.json
- src/lib/server/endpoints/cohere/endpointCohere.ts
- src/lib/server/endpoints/endpoints.ts
- src/lib/server/models.ts
Found myself needing to test stuff from their API, so ended up just adding support for their SDK directly
> Add support for cohere endpoints

- package-lock.json
- package.json
To correspond with v0.8 release.
> Update package.json version

- .env.template
Tested the template with system prompt and without, seems to work well. It's quite fast already 🚀 
This specific config will work as soon as the 32k context window is up
> Add new model to HuggingChat config

- .env.template
- PRIVACY.md
I've been reluctant to do this in the past because it's a one-way change (we can probably never start sharing conversation data with model authors again in the future from this app),
but internal discussion brought this subject again and i think it's as good a change as any
> Privacy update

- src/routes/api/assistant/[id]/+server.ts
add an endpoint /chat/api/assistant/[id] to get an assistant by id.
> add an endpoint to api to get an assistant by id

- src/lib/server/embeddingEndpoints/transformersjs/embeddingEndpoints.ts
Just a test to see if the memory consumption goes down
> Dispose of embeddings pipeline occasionally to clear memory

- src/routes/assistants/+page.server.ts
- src/routes/assistants/+page.svelte
Switched the default sorting from 'popular' to 'trending'.
WHY?? : Because everything on hugging face as default sort by trending
> Sort by Trending to default

- .github/workflows/deploy-prod.yml
* remove package version (sha only)
* remove QEMU
* Rename step
> Clean up internal image action

- package-lock.json
- package.json
Want to make a release to go with the new docker image process
> Bump version to 0.8.4

- src/lib/server/database.ts
- src/routes/admin/stats/compute/+server.ts
This pull request fixes #1111 by using an arrow function instead.
> Fix context of logger

- chart/env/prod.yaml
Reverts huggingface/chat-ui#1132
> Revert "Uses temperature 0.0 for Phi-3."

- package-lock.json
- package.json
Bumps playwright to resolve an issue with `npx playwright install` not working
> chore: bump playwright

- src/lib/components/OpenWebSearchResults.svelte
- src/lib/components/chat/ChatMessage.svelte
- src/lib/server/textGeneration/tools.ts
- src/lib/server/tools/index.ts
- src/lib/types/MessageUpdate.ts
- src/lib/types/Tool.ts
- src/lib/utils/messageUpdates.ts
Adds an indicator in the UI when the tool fails to run as well as providing the error message for debugging. Also fixes an issue with web search infinitely loading after erroring.
> Add error message for tools

- src/lib/server/websearch/scrape/scrape.ts
Another fix for playwright that ensures that we always close the playwright page. When the parsing failed or the content type wasn't html, the page leaked and never got closed.
> Always close playwright page

- src/lib/server/websearch/scrape/scrape.ts
Removes the `Parsing failed` messages from the UI during web search to hopefully lead to less confusion
> Log parsing failures, drop from UI

- src/lib/components/chat/ToolUpdate.svelte
> Clear animation when done

- src/lib/components/chat/ChatMessage.svelte
- src/lib/components/chat/ToolUpdate.svelte
- src/lib/types/Tool.ts
- src/routes/+layout.server.ts
This uses the prometheus metrics, takes the 90th percentile to estimate the size of the loading bar with a default to 15s.
The bar finishes quickly if done early, or hangs close to the end if late.
https://github.com/huggingface/chat-ui/assets/25119303/6476bbce-cb07-47d6-be14-1bdd5743872c
> Add a loading bar for tools

- src/lib/server/tools/images/editing.ts
- src/lib/server/tools/images/generation.ts
Requests the model be concise on image edit and generation outputs
> feat: request model be concise on tool image outputs

- src/lib/components/chat/AssistantIntroduction.svelte
- src/lib/components/chat/ChatWindow.svelte
> Assistants: add reset to default model button

- src/lib/components/chat/ToolUpdate.svelte
Fixes an issue where a tool erroring wouldn't trigger an update in the UI
> fix: tool error not updating in UI

- src/lib/migrations/routines/06-trim-message-updates.ts
`new ObjectId(6)` does not return the same value every time :sweat_smile: 
Replaced it with `new ObjectId("000000000006")` which does
> Fix migration object id

- src/lib/components/chat/ChatInput.svelte
- src/lib/components/chat/ChatWindow.svelte
Adds support for pasting files as an alternative to using the file picker or dropzone. Checks that the input has been focused before accepting the paste
> feat: support file pasting in chat input

- src/lib/server/textGeneration/index.ts
Skips requesting the model pick tools when all of the tools have been disabled in the UI.
> feat: skip tools when all disabled

- src/lib/server/endpoints/cloudflare/endpointCloudflare.ts
> Add sampling parameter support to cloudflare

- src/routes/conversation/[id]/+server.ts
Not sure why the rate limiting broke but this will fix it temporarily at least
> Add createdAt filter on messageEvents

- src/lib/assistantStats/refresh-assistants-counts.ts
- src/lib/server/endpoints/cloudflare/endpointCloudflare.ts
- src/lib/server/endpoints/langserve/endpointLangserve.ts
- src/lib/server/endpoints/llamacpp/endpointLlamacpp.ts
- src/lib/server/models.ts
- src/lib/server/websearch/scrape/playwright.ts
- src/lib/server/websearch/scrape/scrape.ts
Corrected the use of `logger.error(obj:any,msg:string)` which enabled correct logging of errors and ease of debugging.
> Refactor logger error messages for consistency.

- chart/env/prod.yaml
/cc https://github.com/huggingface/chat-ui/pull/1336
> fix: prod registry repository

- src/routes/+layout.svelte
> fix(disclaimer): only show disclaimer if PUBLIC_APP_DISCLAIMER is 1

- src/lib/server/textGeneration/title.ts
env.LLM_SUMMARIZATION is not working because env var is string type.
> fix(env) enable LLM_SUMMARIZATION

- chart/env/prod.yaml
- src/routes/login/callback/updateUser.ts
Forgot the `env.` prefix :facepalm:
> fix(featureflags): use correct env vars

- src/lib/components/chat/ChatMessage.svelte
- src/lib/components/chat/UploadedFile.svelte
- src/lib/components/players/AudioPlayer.svelte
> feat(media): support audio & video files

- .env
- src/lib/server/websearch/search/endpoints.ts
- src/lib/server/websearch/search/endpoints/bing.ts
- src/lib/types/WebSearch.ts
- src/routes/+layout.server.ts
I have created this PR if someone prefers using BING search
Please let me know if there are any issues that i have overlooked in the current implementation
Thanks
> Websearch using Bing API

- src/lib/server/endpoints/openai/openAIChatToTextGenerationStream.ts
- src/lib/server/endpoints/openai/openAICompletionToTextGenerationStream.ts
> fix(openai): do not throw "Generation failed" when finish_reason="length"

- src/routes/settings/(nav)/+layout.svelte
> feat(assistants): better distinction between my own assistants and other people's assistants

- src/lib/utils/formatUserCount.ts
> extend user count

- src/lib/server/textGeneration/tools.ts
Fixes reported issues on huggingchat
> fix(assistants): only enable websearch on assistants with RAG

- src/lib/migrations/routines/02-update-assistants-models.ts
- src/lib/server/models.ts
used to transfer assistants to new models if specified
> feat(models): add transferTo property on old models

- chart/env/prod.yaml
requires #1453 to be merged first to transfer assistants properly
> chores(hchat): update cohere command R+ to latest version

- src/lib/components/chat/ChatWindow.svelte
- src/lib/components/chat/ModelSwitch.svelte
- src/lib/server/models.ts
- src/routes/conversation/[id]/+server.ts
very simple popup that lets you switch models 
requested [here](https://huggingface.co/spaces/huggingchat/chat-ui/discussions/565)
> feat(conv): let user switch models on conversations with deprecated models

- src/lib/server/textGeneration/tools.ts
- src/routes/api/tools/search/+server.ts
> fix(assistants): remove websearch from assistant tool options, add websearch in backend logic

- src/routes/tools/+page.server.ts
- src/routes/tools/+page.svelte
port the behaviour we have on assistants to the tools page
> feat(tools): add toggle to see unfeatured tools for admins

- chart/env/prod.yaml
& ran prettier on the `MODELS` var in `prod.yaml`
> feat(huggingchat): add Qwen 2.5 72B

- chart/env/prod.yaml
Removes older models and adds some newer ones
> feat(huggingchat): Model update 24/09/2024

- src/lib/components/ModelCardMetadata.svelte
- src/lib/server/models.ts
- src/lib/types/Model.ts
- src/routes/+layout.server.ts
- src/routes/api/models/+server.ts
- src/routes/settings/(nav)/[...model]/+page.svelte
> feat: add link to API playground for compatible models

- package-lock.json
- package.json
- src/routes/conversation/[id]/output/[sha256]/+server.ts
see https://huggingface.slack.com/archives/C03Q18WK18T/p1722639880087169
> feat: add content disposition to file endpoint

- src/lib/server/endpoints/endpoints.ts
- src/lib/server/endpoints/openai/endpointOai.ts
- src/lib/server/endpoints/tgi/endpointTgi.ts
- src/lib/server/textGeneration/generate.ts
- src/lib/server/textGeneration/tools.ts
Adds conv ID as a custom header `ChatUI-Conversation-ID`  when calling TGI for better caching
> feat(endpoints): Add conv ID to headers passed to TGI

- src/lib/components/chat/ChatIntroduction.svelte
- src/lib/components/chat/ChatWindow.svelte
- src/routes/+page.svelte
there was a bug that prevented users from uploading images to assistants before starting a conversation
> fix: upload of files on multimodal assistant on first message

- .env
- chart/env/prod.yaml
- svelte.config.js
> feat(security): add flag for allowing iframes

- src/lib/server/endpoints/google/endpointVertex.ts
This has no impact but I forgot to remove application/pdf from images supportedMimeTypes
> [fix] Fix typo in Vertex

- src/lib/components/chat/ChatWindow.svelte
- src/routes/+layout.server.ts
> fix: show file upload button when assistant has tool with file support

- src/routes/settings/(nav)/assistants/[assistantId]/+page.svelte
- src/routes/tools/[toolId]/+page.svelte
https://huggingface.co/spaces/huggingchat/chat-ui/discussions/589
> feat: add confirmation popup before deleting content

- src/lib/server/models.ts
changes the default so that we can make the smallest valid config simpler
Now the `tokenizer` will be found by default if your `model.id` is available on the hub
> feat: use model id as fallback for finding a tokenizer

- .github/workflows/lint-and-test.yml
- package-lock.json
- package.json
- scripts/setupTest.ts
- can run tests without mongo locally
- each suite of test gets a different db
> feat(test): use mongo in memory for tests

- src/lib/components/CodeBlock.svelte
also simplifies the CodeBlock component
> fix: syntax highlighting works in SSR

- src/lib/components/ScrollToPreviousBtn.svelte
One liner to update the query selector for the Scroll to Previous button
> Small fix for Scroll Previous Button

- src/routes/tools/+page.svelte
- src/routes/tools/[toolId]/+page.svelte
> feat: add warnings to let people know they should use a tool calling model

- chart/env/prod.yaml
waiting for context window values before merging
> feat(hchat): add QwQ to prod config

- chart/env/prod.yaml
- src/lib/components/OpenWebSearchResults.svelte
- src/lib/components/chat/ChatMessage.svelte
- src/lib/components/chat/MarkdownRenderer.svelte
- src/lib/components/chat/OpenReasoningResults.svelte
- src/lib/server/generateFromDefaultEndpoint.ts
- src/lib/server/models.ts
- src/lib/server/textGeneration/generate.ts
- src/lib/server/textGeneration/reasoning.ts
- src/lib/server/textGeneration/title.ts
- src/lib/server/websearch/search/generateQuery.ts
- src/lib/types/Message.ts
- src/lib/types/MessageUpdate.ts
- src/lib/utils/getReturnFromGenerator.ts
- src/routes/conversation/[id]/+page.svelte
- src/routes/conversation/[id]/+server.ts
https://github.com/user-attachments/assets/4629f8b0-d535-4039-9aac-cc5d3593a338
> feat: UI for advanced reasoning models

- chart/env/prod.yaml
- package-lock.json
- package.json
- src/lib/server/models.ts
- src/lib/server/textGeneration/tools.ts
- src/lib/server/websearch/search/endpoints/bing.ts
more up to date with latest changes in transformers lib and also adds tool calling to qwen 2.5 72b
> feat: improve tool calling & add tools to qwen 2.5 72b

- src/routes/+layout.svelte
Fixes UI: The panel arrow appears over the settings dialog #1659
> fix: collapse arrow no longer visible on top of settings modal

- src/lib/components/chat/Alternatives.svelte
- src/lib/components/chat/ChatMessage.svelte
- src/lib/components/chat/Vote.svelte
Refactoring vote & alternative components from `ChatMessage.svelte`
> Refactor vote & alternative components

- src/lib/components/chat/ChatInput.svelte
> fix: show file picker for assistant with mime types

- chart/env/prod.yaml
not sure about this one all I know is the model can be found at api-inference.endpoints.huggingface.tech/models/CohereLabs/[...]
> fix(cohere): 404 due to org rename

- .env.ci
- .github/workflows/lint-and-test.yml
- package-lock.json
- package.json
we were already making sure the docker image builds, but not if it runs well. there are some edge cases where the docker image will build correctly but not run and give a 500. This will let us catch those errors early
> feat(ci): add a health check after building the docker image

- docs/source/configuration/models/overview.md
- docs/source/configuration/web-search.md
nothing fancy, just fixed some typos
> docs: correct typos and grammar

- chart/env/prod.yaml
cc @rtrompier we're no longer targeting the main branch on prod so i will merge this on the correct branch
> fix: reduce min pods following closure on correct branch

- src/lib/migrations/lock.ts
- src/lib/server/auth.ts
- src/lib/types/Semaphore.ts
- src/routes/login/callback/updateUser.ts
automatically refresh oauth token if refresh token mechanism is available, 5 minutes before oauth token expiration
cc @gary149 
Follow up #1900
> Automatically refresh oauth token
