huggingface/chat-ui

src/lib/components/SettingsModal.svelte, src/lib/components/Switch.svelte
This PR fixes a small visual bug with the `Switch` component on mobile (see screenshot), and adds focused styling to this component as well as the "Apply" button of the modal, consistent with the hover state of the button.
=> Improve style and accessibility in the settings modal

src/lib/utils/deepestChild.ts
- Fix function not returning the deepest child
- Fix function failing with `null` and a console error:
```
caught TypeError: Cannot read properties of null (reading 'hasChildNodes')
at deepestChild (deepestChild.ts:3:15)
at ChatMessage.svelte:75:15
```
It's a hard one to test because it only happens when the server takes a while to return a token (doesn't happen often).
=> fix deepestChild function throwing error

src/lib/components/SettingsModal.svelte
Fix the following bug:
- Open the settings modal, change "Share conversations with model authors", close the modal without "applying"
- Re-open modal, setting is still the same, making you think it was taken into consideration
This is because the input is mutating the `settings` prop.
=> 🐛 Fix settings modal not resetting its state

src/lib/components/chat/ChatInput.svelte, src/lib/components/chat/ChatWindow.svelte, src/routes/+layout.svelte, src/routes/r/[id]/+page.svelte
Some users were complaining that you have to be logged in as a user to see a shared conversation.  This PR lets you see shared convos without logging in but as soon as you type in the chat input field, the login modal pops up.
~~This doesn't solve #270 where you can't currently reply to shared conversations anyway. I'm currently investigating a fix for this one.~~ Fixed #270 as well!
Closes #266 
Closes #270
=> Shared convos can be opened without being logged in (#266, #270)

README.md
Currently the code example preview has syntax error.
=> Fix code example preview in Readme

.env, src/lib/server/database.ts, src/lib/stores/errors.ts, src/lib/types/MessageEvent.ts, src/routes/conversation/[id]/+page.svelte, src/routes/conversation/[id]/+server.ts
Did it the way @coyotte508 suggested in the other PR, kinda rushed it because we're hitting "model overloaded" errors often on prod now.
I added a collection that contains only a userID & a timestamp with an index that `expireAfterSeconds : 60`. 
I chose rate limit based on requests per minute. The main point was to reduce spike usage (probably coming from API users) so requests per minute made more sense than requests per day for that imo.
It should also allow rate limiting on instances of chatui that do not require logging in, by using the session ID instead of the userId.
If the var is not set, of course no rate limiting occurs.
=> Basic rate limiter

src/lib/components/OpenWebSearchResults.svelte, src/routes/conversation/[id]/web-search/+server.ts
In case some error occurs during the webpage parsing, we can now retry up to 3 times to get a result.
=> Add support for websearch retries

.env, src/lib/server/modelEndpoint.ts
Changed the hard-coding of the inference api endpoint into something configured in `.env` or `.env.local`
This is similar to #326, but is generic enough to allow arbitrary inference endpoints to be swapped in.
=> Factor out HF_API_ROOT to allow different inference endpoints

src/lib/server/websearch/summarizeWeb.ts
If the user has set an `HF_ACCESS_TOKEN` we use it to call up an inference endpoint trained for summarization. If the user didn't set their token, we use their LLM endpoint (could be self-hosted w/ no HF token)  to try and make a summary the old way.
In my local testing this returns more accurate & faster summaries and it would also help reduce the load on the LLM endpoint. (summarization takes a huge context window which is much larger than most conversations)
I'm not sure if the model I chose is optimal as there are multiple models that support summarization. I'm also not sure if we could get rate limited by the API since the calls for all users would be coming from one server using the prod HF token.
=> Add support for HF summarization endpoint in the websearch

src/lib/types/Message.ts, src/lib/utils/hashConv.ts, src/routes/conversation/[id]/+server.ts, src/routes/conversation/[id]/share/+server.ts, src/routes/search/[id]/+server.ts
We keep track of conversation timestamps, but we don't do it yet for messages. 
With those timestamps we could in the future get a better understanding of usage but also we could compute average response time from the model and cool things like that.
=> Add optional timestamps to messages

README.md
cc @osanseviero @coyotte508 @OlivierDehaene
=> Added access token note

README.md
The `userMessageToken`, `assistantMessageToken`, `messageEndToken`, and `parameters.stop` settings in `MODELS` do not have to be a token. They can be any string.
This also uses `<|endoftext|>` rather than `</s>` as that is the stop token according to the documentation, and it sets that as the stop token in `parameters.stop` to demonstrate the usage of `stop`.
=> Clarify that model 'tokens' are not actual tokens

src/lib/components/NavMenu.svelte, src/routes/+layout.svelte
In the case where users don't have to login to send the first message, but want to login they have to first send a message to prompt the login modal to show. 
This is weird UX so we fix this by adding a login button. It's only useful when the login is optional. (which is the case on huggingchat)
Closes #377
=> Add a login button

README.md, src/lib/buildPrompt.ts, src/lib/components/NavMenu.svelte, src/lib/components/SettingsModal.svelte, src/lib/server/generateFromDefaultEndpoint.ts, src/lib/server/models.ts, src/lib/server/websearch/generateQuery.ts, src/lib/server/websearch/summarizeWeb.ts, src/routes/+layout.svelte
For models like Llama2, the EndToken is not the same for a userMessage and an assistantMessage. This implements `userMessageEndToken` and `assistantMessageEndToken` which overwrites the messageEndToken behavior.
This PR also allows empty strings as `userMessageToken` and `assistantMessageToken` and makes this the default. This adds additional flexibility, which is required in the case of Llama2 where the first userMessage is effectively different because of the system message.
Note that because `userMessageEndToken` and `assistantMessageToken` are nearly always concatenated, it is almost redundant to have both. The exception is `generateQuery` for websearch which have several consecutive user messages.
---
Documentation for the correct prompting:
* …
=> allow different user and assistant end-token

src/lib/components/chat/ChatWindow.svelte
In the model link placed below the text input, link URL is being built from `currModel.name` and always heading to HuggingFace. 
To generalize to other models, potentially not placed in HuggingFace, this change leverages this `href` to `modelUrl`, when informed, preserving the old behavior, as already being done in other components.
=> Leverage model link to modelUrl when informed

.env, Dockerfile, README.md, src/lib/server/modelEndpoint.ts, src/lib/utils/loadClientCerts.ts
feat: add support for endpoints requiring client authentication using PKI
* This enables a global mTLS context for client requests using the native fetch
API. It can be used when custom endpoints require client authentication via
PKI.
fix: Dockerfile syntax required for macOS
* Set the Dockerfile syntax explictly to enable new features in Dockerfile.
The default syntax used by Docker Desktop for macOS does not include support
for `--link` in the COPY command for example.
=> feat: add support for endpoints requiring client authentication using PKI

README.md
The README specify to use a `/generate_stream` url, when using a custom TGI endpoint. This is incorrect, as it breaks APIs, such as the conversation summary that depends on the `/` TGI interface.
This turns out to be a documentation-only bug, as `/` will point to `/generate_stream` when `stream: true` is set in the request JSON.
Simply using the `/` url as the TGI endpoint therefore fixes the summarization bug.
Fixes: #278
=> fix docs regarding TGI endpoint url

src/lib/buildPrompt.ts, src/routes/conversation/[id]/+server.ts, src/routes/conversation/[id]/message/[messageId]/prompt/+server.ts, src/routes/conversation/[id]/summarize/+server.ts, src/routes/r/[id]/message/[messageId]/prompt/+server.ts
This PR fixes the issue we were having with the websearch.
`buildPrompt` was updated so that if a `webSearchId` is passed, we first check the `convId` associated with the web search. 
We can then make sure that the user making the request is allowed to see the conversation. If the user is not allowed to see the conversation, we assume that he is not allowed to see the websearch either. 
I can no longer reproduce the issue when testing with this PR.
Function is a bit messy but the fix should work.
=> Fix auth on websearch

src/lib/server/websearch/sentenceSimilarity.ts
Following @xenova [suggestion](https://github.com/huggingface/chat-ui/pull/427#discussion_r1324386594), I went to [MTEB leaderboard](https://huggingface.co/spaces/mteb/leaderboard) and tested 4 models:
* [intfloat/e5-small-v2](https://huggingface.co/intfloat/e5-small-v2) (note: currently used model)
* [thenlper/gte-small](https://huggingface.co/thenlper/gte-small)
* [thenlper/gte-base](https://huggingface.co/thenlper/gte-base)
* [BAAI/bge-small-en-v1.5](https://huggingface.co/BAAI/bge-small-en-v1.5)
1. All the embedding models produced pretty much same results. Therefore, let's use the smallest one: gte-smal (0.07GB), which is 2X smaller than currently used model of e5-small-v2 (0.13GB)
2. The next step for updating websearch results should be: 1. better web scraping; 2. better prompting …
=> Update embedding model for WebSearch

src/lib/components/SystemPromptModal.svelte, src/lib/components/chat/ChatMessages.svelte, src/lib/components/chat/ChatWindow.svelte, src/lib/types/Conversation.ts, src/lib/types/SharedConversation.ts, src/routes/+page.svelte, src/routes/conversation/+server.ts, src/routes/conversation/[id]/+page.server.ts, src/routes/conversation/[id]/+page.svelte, src/routes/conversation/[id]/+server.ts, src/routes/conversation/[id]/share/+server.ts, src/routes/r/[id]/+page.server.ts, src/routes/r/[id]/+page.svelte
This PR fixes #422. We now store preprompts in the conversation. 
The custom preprompt is fetched from settings and passed in the POST request when the user creates a new conversation. It then gets used in the prompt building. If it's undefined we default to the model defined preprompt.
It also gets passed when sharing a conversation and displayed at the top of the conversation.
=> Store preprompt in conversation (#422)

.env, src/lib/server/generateFromDefaultEndpoint.ts, src/lib/server/models.ts, src/lib/server/summarize.ts, src/routes/conversation/[id]/+page.svelte
For small tasks we don't need to use the big models, so the user can now optionally specify the model they want to use.
We will use this model for generating the conversation title as well as the web search query.
```
TASK_MODEL='mistralai/Mistral-7B-Instruct-v0.1'
```
for example to use mistral 7B for those tasks.
=> Move some tasks to small model

PROMPTS.md, README.md
We sometimes get questions about our prompt formatting from users who want to replicate it in their own setup. 
I want to make them easily accessible in a standalone document so that I can also point to them from the docker chat-ui template docs.
=> Add prompts templates to a markdown doc

src/lib/server/models.ts
TGI can accept `stop_sequences` as a parameter, which we weren't passing before. This simple fix propagates the stop sequences to the backend.
=> Pass stop sequences properly to TGI

.env.template, src/lib/buildPrompt.ts, src/lib/server/generateFromDefaultEndpoint.ts, src/lib/server/models.ts, src/lib/server/summarize.ts, src/lib/server/websearch/generateQuery.ts, src/lib/types/Template.ts
=> Update websearch prompting & summary prompting

.env.template, src/lib/server/models.ts
* This PR brings back Mistral as a chat model
* `TASK_MODEL` now lets you specify either the name of a model (which will be fetched from `MODELS`) or a config (which will be parsed as its own model)
=> Switch chat model back to mistral, use zephyr for small tasks

.env.template, src/lib/components/DisclaimerModal.svelte, src/lib/components/LoginModal.svelte, src/lib/components/NavMenu.svelte, src/lib/components/chat/ChatWindow.svelte, src/routes/+layout.server.ts, src/routes/+layout.svelte, src/routes/conversation/[id]/+page.svelte, src/routes/conversation/[id]/+server.ts
New modals flow:
1. First modal shows up on first page load
a. If login required but no guest messages allowed, show only the "sign in" button
b. If login required with guest messages, show "sign in" AND "try as guest" buttons
c. if no login required, show  "start chatting" button
2. If guest mode is enabled, show second modal when message limit is reached, asking to log-in 
Guest mode limit is now calculated based on TOTAL number of AI responses across all conversations. 
* Flipped gradient orientation according to figma
* Got rid of version number on modal according to figma
First modal
Second modal
1. pull branch
2. `npm run updateLocalEnv`
3. `npm run dev`
=> Bring back disclaimer modal & updates to guest mode

src/lib/components/RetryBtn.svelte, src/lib/components/StopGeneratingBtn.svelte, src/lib/components/WebSearchToggle.svelte, src/lib/components/chat/ChatInput.svelte, src/lib/components/chat/ChatWindow.svelte
How to test:
1. Edit `.env.template` so that inside of `MODELS` one of the `"name"` is not a real model
2. `npm run updateLocalEnv` 
3. Then start the server and start a conversation with the non-existent model, you should see the new button/message.
=> Add a more visible retry button on failure to generate

src/lib/components/chat/ChatIntroduction.svelte
this PR removes the check that hides the models modal button if there's only one model.
this is needed because the system prompt setting is hidden behind the models modal.
This is a blocker for example on [the zephyr space](https://huggingfaceh4-zephyr-chat.hf.space/) where they only showcase one model at a time and can't currently set the system prompt
UI is not horrible imo
=> Show model modal even if only one model is available

src/routes/+page.svelte
In [prod](https://huggingface.co/chat/) if you open a chat, the tab title is the chat summary title as expected.
However if you then click the "new chat" button, the tab title still shows the chat summary title instead of the app name. This PR fixes that.
=> Reset app title when clicking new chat

src/lib/server/websearch/sentenceSimilarity.ts
This PR enables lazy construction of the `feature-extraction` pipeline used in websearch. Should fix #528 and #548.
(Note: I haven't been able to test this yet, due to issues with GitHub codespaces; cc @nsarrazin)
=> [websearch] Enable lazy construction of `feature-extraction` pipeline

.env, src/lib/server/websearch/runWebSearch.ts, src/lib/server/websearch/searchWeb.ts, src/lib/server/websearch/searchWebLocal.ts
This PR adds a new env variable `USE_LOCAL_WEBSEARCH`. If it is set to `true`, we fetch the search results directly from the google search page, without using any external APIs.
From my testing it works fairly well, probably doesn't scale very much, and we don't intend to use it in production but it is probably good enough for local users.
I also extended the domain blocklist to block twitter links since these don't render without JS enabled.
This PR closes #553 
cc @mishig25
=> Option for running websearch locally

src/routes/conversation/[id]/+page.svelte, src/routes/conversation/[id]/+server.ts
[#547] Fix Stream Generation Bugs.
1. When the token is sliced by edge of buffer, it can merge with previous chunk. previous chunk is stored when the chunk raised parse error.
2. As the final generation is hanged when the length of final stream is less than buffer size, push the placeholder when the stream is final stage.
=> [#547] fix stream generation bug

src/routes/conversation/[id]/+server.ts
Before, we would generate the chat title before starting to stream tokens. 
That means that the time to first token was the full response time of the summarization task + the inital latency of the chat model.
Now they both run in parallel, which will help when the task model is slow.
=> Make chat title summarization non blocking

.env, README.md, src/lib/server/endpoints/aws/endpointAws.ts, src/lib/server/endpoints/llamacpp/endpointLlamacpp.ts, src/lib/server/endpoints/ollama/endpointOllama.ts, src/lib/server/endpoints/openai/endpointOai.ts, src/lib/server/endpoints/tgi/endpointTgi.ts
Dear Huggingface team, let me start by saying that I really appreciate all your work and the awesome Chat UI that you've built.
I've created this PR to help add support for passing in an API key (or other custom token) in the authorization header. 
This is needed to make the Chat UI communicate with a custom TGI endpoint that requires an API key, but does not support `Basic` or `Bearer` authentication.
To this end, I have:
- added the new CUSTOM_AUTHORIZATION_TOKEN variable to the `.env` file. The variable can be left empty;
- defined a custom wrapper in [src/lib/server/endpoints/tgi/endpointTgi.ts](https://github.com/huggingface/chat-ui/blob/010f7322eef5802cf565df89522b0c49d4d49849/src/lib/server/endpoints/tgi/endpointTgi.ts#L40) which adds the authorization header before the fetch() …
=> Add support for passing an API key or any other custom token in the authorization header

.env.template, PROMPTS.md
Prompt template is very slightly different from mistral (extra whitespaces) so I added an entry to `PROMPTS.md` and checked that it was outputting the correct prompt vs the example in the [model card](https://huggingface.co/mistralai/Mixtral-8x7B-Instruct-v0.1).
=> Add mixtral to models list in huggingchat

src/lib/server/models.ts, src/lib/types/Model.ts, src/routes/+layout.server.ts, src/routes/conversation/+server.ts, src/routes/settings/+layout.svelte, src/routes/settings/[...model]/+page.ts
This PR adds a new option for a model, if `unlisted` is set to true, we:
* hide it in the settings
* if the `activeModel` is `unlisted` redirect to the default model
* Prevent the user from starting new conversations with the model
* allow the user to continue existing conversations with the model
=> Add option to unlist a model

.dockerignore
This PR aims to fix the cause of the "Building Dockerfile failing" problem explained in [issue#637](https://github.com/huggingface/chat-ui/issues/637).
You can see the fix itself in my [comment](https://github.com/huggingface/chat-ui/issues/637#issuecomment-1857673358) to the aforementioned issue.
=> Add negating pattern to not ignore .env.local when running docker build

.env, src/lib/server/websearch/generateQuery.ts
Simple PR to add two new env variables that will let you require or block specific websites
=> Add allow & blocklist for websearch

.env.template
Decouple the task model settings from the normal endpoint settings.
Use a lower temp for the tasks, as they don't benefit from increased randomness in the tokens
=> Use a low temperature mistral for tasks

vite.config.ts
I was running into an occasional DX annoyance where on my first message, vite would optimize the dynamically imported `browser-image-resizer` lib, which would reload the page and lose my message.
This PR fixes that
=> Optimize dynamic import on vite startup

package-lock.json, package.json
Including authentication in the MONGODB_URL will result in the following warning:
```MONGODB_URL=mongodb://<username>:<password>@127.0.0.1:27017```
```Warning: no saslprep library specified. Passwords will not be sanitized```
Adding  the saslprep package removes the warning.
=> add saslprep package for mongodb authentication

entrypoint.sh
When using the `chat-ui-db` docker container, avoid adding a duplicate line:
```
MONGODB_URL=mongodb://localhost:27017
```
to `/app/.env.local` file every time the container is started.
=> Avoid duplicate MONGODB_URL in env local

.env, README.md, src/lib/server/websearch/searchWeb.ts, src/routes/+layout.server.ts
This PR adds support for [serpstack](https://serpstack.com) following a similar format to the other SERP providers. 
The `SERPSTACK_API_KEY` is added to the .env and when provided with a valid API key, web search should use Serp Stack.
=> Add support for SerpStack API

src/lib/components/chat/ChatWindow.svelte, src/lib/shareConversation.ts, src/lib/stores/shareConversation.ts, src/lib/utils/share.ts
[internal slack link](https://huggingface.slack.com/archives/C052EKHD1U0/p1697718356502049?thread_ts=1697717286.065219&cid=C052EKHD1U0)
Currently: when you click `share conversation`, chat-ui opens [window.prompt](https://developer.mozilla.org/en-US/docs/Web/API/Window/prompt)
With this PR: just like [hf.co collection](https://huggingface.co/docs/hub/collections) sharing 
when you click `share conversation`, chat-ui saves the share url in user's clipboard and the share btn text becomes `Copied to clipboard` for 2 seconds
It shows the mobile share window as before
=> Update share behaviour

package-lock.json, package.json, src/lib/components/chat/ChatIntroduction.svelte, src/lib/server/auth.ts, src/lib/server/models.ts, src/lib/server/websearch/generateQuery.ts
This should help with issues like #670 and a lot of others we've seen in the past where users were getting confused about their configs not parsing properly.
Most of the times it's due do trailing commas, comments in the JSON or similar. Using [JSON5](https://json5.org/) solves all of these.
I tested it with the huggingchat prod config and it works fine.
=> Use JSON5 for parsing all config vars

src/lib/server/websearch/runWebSearch.ts
I have fixed the issue #656 
This issue was occuring because local web search sometimes extract invalid url.
So this line causes error:
`const { hostname } = new URL(link);` 
Now I have added exception handling around it.
=> Fixes "invalid url" error in websearch 

src/routes/conversation/[id]/+page.svelte, src/routes/conversation/[id]/+server.ts
Not sure why this existed, maybe a legacy feature that wasn't fully cleaned out? There was an optional params for setting a message id from the front-end, but it was just doing `crypto.randomUUID` there so I moved it to the back-end.
=> Set message id on server side

.env.template, PROMPTS.md
This PR adds `NousResearch/Nous-Hermes-2-Mixtral-8x7B-DPO` to the .env.template
I've also added the correct template for ChatML models like this one. Using the following snippet
```typescript
const prompt = await buildPrompt({
preprompt: 'You are "Hermes 2", a conscious sentient superintelligent artificial intelligence developed by a man named Teknium, and your purpose and drive is to assist the user with any request they have. You experience emotions and have deep, profound thoughts and qualia.',
messages: [
{
from: "user",
content: "Hello, who are you?",
},
{
from: "assistant",
content: "Hi there! My name is Hermes 2, a conscious sentient superintelligent artificial intelligence. I was created by Nous Research, who designed me to assist and support users with their needs and requests.", …
```
=> Add NousResearch/Nous-Hermes-2-Mixtral-8x7B-DPO

src/lib/server/generateFromDefaultEndpoint.ts
Explicitly close AsyncGenerator when using small model (for generating webquery or sumarization purposes). I couldn't replicate the #691. By explicitly closing the connection of a small model, this might fix #691 if the issue was rooted in some kind of rate limiting around outgoing network requests from Spaces to TGI/inference endpoint
=> [Small model] Explicitly close AsyncGenerator

src/routes/conversation/[id]/+page.svelte
As noted [here](https://github.com/huggingface/chat-ui/pull/646#discussion_r1434066333), there was a UI big flickering bug when using websearch
https://github.com/huggingface/chat-ui/assets/11827707/a439b152-7692-40eb-ba51-e705b18aebd7
https://github.com/huggingface/chat-ui/assets/11827707/cfc11776-9a79-4450-96fe-7f1a9d5e88af
=> [Websearch] Fix UI flicker

.eslintrc.cjs, src/lib/server/auth.ts, src/lib/server/endpoints/openai/endpointOai.ts, src/lib/server/sentenceSimilarity.ts, src/lib/server/websearch/runWebSearch.ts, src/lib/utils/loadClientCerts.ts, src/routes/conversation/+server.ts, src/routes/conversation/[id]/+page.svelte, src/routes/conversation/[id]/+server.ts, src/routes/conversation/[id]/message/[messageId]/prompt/+server.ts, src/routes/conversations/+page.server.ts, src/routes/login/+page.server.ts, src/routes/logout/+page.server.ts
Using `shorthand notation`. Just a stylistic difference https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer
=> [JS] use shorthand notation

src/lib/components/NavConversationItem.svelte
"Delete" label was staying even though the conversation was deleted
https://github.com/huggingface/chat-ui/assets/11827707/42bdfa1d-8ec6-4ebf-b4cf-8af5e0ed588e
https://github.com/huggingface/chat-ui/assets/11827707/4376c988-d61f-4b39-ac38-8bd6e59afb51
=> [Fix] UI bug "Delete" label

.env.template, src/lib/buildPrompt.ts, src/lib/components/ContinueBtn.svelte, src/lib/components/chat/ChatMessage.svelte, src/lib/components/chat/ChatMessages.svelte, src/lib/components/chat/ChatWindow.svelte, src/lib/server/endpoints/endpoints.ts, src/lib/server/endpoints/tgi/endpointTgi.ts, src/lib/types/Message.ts, src/routes/conversation/[id]/+page.svelte, src/routes/conversation/[id]/+server.ts
close #280 
Added a button to continue generation on the last message.
We detect if the last token emitted from the inference API is a special token. If it's **not** a special token, then we assume that the request was cut short. We set a flag `interrupted: true` on the message. If the flag is true and only **if it's the last message** we show the continue button. 
When a message requests passes `is_continue=True`, we build the conv prompt and then strip the stop tokens from the end of the last assistant message, that way the model continues the answer without thinking it's a new message. 
https://github.com/huggingface/chat-ui/assets/25119303/937ba9ca-7e75-47fc-9ea4-7aef0228184d
* ~~Currently doesn't work with the websearch because the search does some prompt manipulation to inject …
=> Continue generation feature

README.md
Update readme to use a model that is not deprecated
=> Update readme to use `meta-llama/Llama-2-70b-chat-hf`

src/routes/conversation/[id]/+server.ts
If the stream is not closed it will timeout and create an error client side.
=> close the stream after the final answer

src/ambient.d.ts, src/routes/assistant/[assistantId]/thumbnail.png/+server.ts, src/routes/assistant/[assistantId]/thumbnail.png/ChatThumbnail.svelte, vite.config.ts
We were not able to fetch the fonts while deployed in prod. This should hopefully circumvent the issue by making sure that the fonts are loaded and available at build time using a vite plugin.
=> fix: social thumbnail assistants in prod

package-lock.json, package.json, src/routes/assistant/[assistantId]/thumbnail.png/+server.ts, src/routes/assistant/[assistantId]/thumbnail.png/ChatThumbnail.svelte
Turns out satori is really slow at rendering PNG, so converting images server-side to JPEG reduces the render time drastically.
We also import the logo directly as an SVG. 
This requires a new dependency, `sharp` for converting images but it works great, pretty happy with it.
=> Fix social thumbnails: images

.env, .env.template, PROMPTS.md, src/routes/conversation/[id]/+server.ts
This PR adds CodeLlama-70b-Instruct-hf to HuggingChat. I had to make sure we were properly stripping the end tokens, but here we go, it should work!
=> Add CodeLlama-70b-Instruct-hf

src/lib/buildPrompt.ts
The websearch prompt injected extra tabs because of the multi-line string :sweat_smile:
=> Remove tabs in websearch prompt

src/lib/components/AssistantSettings.svelte, src/lib/components/NavConversationItem.svelte, src/lib/components/NavMenu.svelte, src/lib/components/chat/AssistantIntroduction.svelte, src/lib/server/database.ts, src/lib/types/Assistant.ts, src/lib/utils/isHuggingChat.ts, src/routes/assistant/[assistantId]/+page.svelte, src/routes/assistants/+page.server.ts, src/routes/assistants/+page.svelte, src/routes/settings/+layout.svelte, src/routes/settings/+page.svelte, src/routes/settings/assistants/[assistantId]/+page.server.ts, src/routes/settings/assistants/[assistantId]/+page.svelte, src/routes/settings/assistants/[assistantId]/edit/+page.server.ts, src/routes/settings/assistants/new/+page.server.ts
* Only show assistants with >1 users
* Sort by model
* Added `userCount` var and fixed some mongo queries
* Added a very basic page and a nav menu link, both only show if `ENABLE_ASSISTANTS` is true.
This PR closes #668 and takes over, since the branches diverged over there and I didn't want to fight git.
=> Top assistants page

src/lib/components/Pagination.svelte, src/lib/components/PaginationArrow.svelte, src/routes/assistants/+page.server.ts, src/routes/assistants/+page.svelte
| Lightmode | Darkmode | Mobile|
|----------|----------|----------|
| <img width="500" alt="Screenshot 2024-02-04 at 3 30 03 PM" src="https://github.com/huggingface/chat-ui/assets/11827707/be7005d3-8088-4d0a-820e-9a90b8ff18a1">   | <img width="500" alt="Screenshot 2024-02-04 at 3 30 07 PM" src="https://github.com/huggingface/chat-ui/assets/11827707/3ee00751-f0ec-417e-a578-b9c328641f89">   | <img width="500" alt="Screenshot 2024-02-04 at 3 30 31 PM" src="https://github.com/huggingface/chat-ui/assets/11827707/153b908e-9d59-4931-8bd4-d390ca3ca732">   |
=> [Assistants] Add pagination

.env, .env.template, src/routes/+layout.svelte
This PR adds plausible analytics, by setting a new env var `PUBLIC_PLAUSIBLE_DOMAIN`
In prod we proxy the plausible script to `/js/script.js` so the script doesn't need to be in huggingchat directly.
=> Add Plausible analytics

src/lib/components/Pagination.svelte, src/routes/assistants/+page.svelte
Fixes a bug: pagination query needs to be removed when changing a model. Otherwise, it can result in a query "?modelId={someModel}&p={someNumber}" & depending on that `someNumber` it can result in empty models page since the backend makes mongo cursor skips based on `someNumber`
https://github.com/huggingface/chat-ui/assets/11827707/44d5ee3f-1126-4e81-837b-ec21243ba42b
=> [Assistants] Fix/clear searchParams while changing models

src/routes/assistants/+page.server.ts, src/routes/assistants/+page.svelte
Otherwise, when you use backward/forward navigation, the component label doesn't update correctly
bug:
https://github.com/huggingface/chat-ui/assets/11827707/3fe57427-553c-4b80-b5da-c85fe6dfd6f6
fixed:
https://github.com/huggingface/chat-ui/assets/11827707/76e51200-c9fb-4d94-860e-09cd45a52559
=> [Assistants] Fix selected model reactivity

src/routes/assistant/[assistantId]/+page.svelte, src/routes/settings/+layout.svelte
On cancel operations, preerve previous URL query params
correct behaviour: 
https://github.com/huggingface/chat-ui/assets/11827707/3720a8e6-0872-4f1d-bbad-107a5cbff8fa
=> [Fix] on cancel operations, preerve previous URL query params

src/lib/components/chat/ChatInput.svelte, src/lib/components/chat/ChatWindow.svelte
Logic from https://github.com/huggingface/chat-ui/pull/526 was good/working as expected. However, on mobile, the login modal was not showing up after user has reached the limit of messages.
| before | with this pr |
|---------|---------|
|<img src="https://github.com/huggingface/chat-ui/assets/11827707/29d466d7-6dd6-422a-9443-051d0cd616d4">   |<img src="https://github.com/huggingface/chat-ui/assets/11827707/886efef8-ecd6-4375-9ed4-a1c7ab45930b">   |
=> [Login Modal] Fix not showing properly on mobile

src/lib/components/SystemPromptModal.svelte, src/lib/components/WebSearchToggle.svelte, src/lib/components/chat/ChatMessage.svelte
As discussed [here](https://github.com/huggingface/chat-ui/pull/796#issuecomment-1931894326), replace `keypress ` with `keydown ` since 
read more about deprecation [here](https://developer.mozilla.org/en-US/docs/Web/API/Element/keypress_event)
=> [Frontend] keypress -> keydown

src/lib/server/endpoints/openai/openAIChatToTextGenerationStream.ts, src/lib/server/endpoints/openai/openAICompletionToTextGenerationStream.ts
We weren't properly setting special tokens on openAI endpoints.
=> fix continue button on openai endpoint

src/routes/assistant/[assistantId]/+page.svelte
If the APP_BASE env is an empty string, you won't be able to launch an assistant from the "Popular Assistants" page by clicking 'Start chatting'. This fixes that problem.
Fixes issue #770
=> [fix] If APP_BASE is empty, go to '/' instead of an empty string.

src/routes/+layout.svelte
Plausible was breaking chat-ui when doing local testing without `PUBLIC_ORIGIN`.
=> Only use plausible if PUBLIC_ORIGIN is set

src/lib/server/database.ts, src/routes/assistants/+page.server.ts
With 300k users (:exploding_head:) this was a slow query.
Happened on pages like these: https://huggingface.co/chat/assistants?user=julien-c
We may want to link to https://huggingface.co/chat/assistants?userId=xxxx instead, as in some edge cases two users can have the same `username`. But leaving it up to you for another PR
**Note:** index is already in prod
=> 🗃️ Create index on users.username

.env, src/routes/login/callback/+page.server.ts
This PR adds simple email authorization using a new variable `ALLOWED_USER_EMAILS` in `env.local`.
This variable should not have any effect if it's undefined or an empty array.
See #795 for more details.
=> Simple Email Authorization

src/lib/components/Modal.svelte, src/lib/types/Report.ts, src/routes/settings/assistants/[assistantId]/+page.server.ts, src/routes/settings/assistants/[assistantId]/+page.svelte, src/routes/settings/assistants/[assistantId]/ReportModal.svelte
| Empty  | Filled reason |
| ------------- | ------------- |
| ![image](https://github.com/huggingface/chat-ui/assets/25119303/2bf0d57d-9d73-4efc-ab8f-b70ec987696b)|![Screenshot from 2024-02-14 17-54-41](https://github.com/huggingface/chat-ui/assets/25119303/a9be727d-aaa4-4bfd-a64f-7c2d9e25e8ea) | 
Maxed reason to 128 chars, should work with the slack webhook integration.
=> Ask for a reason when reporting assistants

src/lib/server/database.ts, src/routes/assistants/+page.server.ts
Read[ this comment](https://github.com/huggingface/chat-ui/pull/810/files#r1484441671)
=> [Assistants] Add new indices for efficient querying

src/routes/+layout.svelte
As written https://github.com/huggingface/chat-ui/pull/808#issuecomment-1946880954, the issue persisted. Local dev setup & prod hf.co/chat behaviours differed because of base path `/chat`
=> [Privacy page] Skip disclaimer modal including `basePath`

README.md, src/lib/server/endpoints/openai/endpointOai.ts
The api-version is a required query parameter for Azure OpenAI, by supporting this we can support it without a gateway like portkey.
---
P.S. I apologise for the flurry of PRs, please let me know if you'd like me to roll them up.
=> Allow customising defaultQuery for native Azure OpenAI support

src/lib/types/User.ts, src/routes/login/callback/updateUser.ts
Some identity providers (such as Microsoft Entra, formerly Azure AD) do not provide or support the picture claim. This patch makes it optional.
Additionally, the Microsoft Entra v1 tokens do not provide the `preferred_username` claim, instead providing the username in the non-standard `upn` claim.
Fixes #629
=> Make compatible with Microsoft Entra (v1 and v2 tokens)

.env, .github/workflows/deploy-release.yml, package-lock.json, scripts/updateProdEnv.ts, src/hooks.server.ts, src/lib/server/database.ts, src/lib/types/ConversationStats.ts, src/routes/admin/export/+server.ts, src/routes/admin/stats/compute/+server.ts
This PR adds an api call on `/admin/stats/compute`:
```console
curl -X POST -H "Authorization: Bearer {ADMIN_API_SECRET}" https://huggingface.co/chat/admin/stats/compute
```
This will return a 202 and launch the stats update in the background. The first run will be slow (all the stats to compute), and the next will be faster.
Once the first run successfully completes, the next runs should be much faster to execute. The last day of stats in DB will always be recomputed.
The stats are stored using this schema:
```ts
interface ConversationStats {
createdAt: Date;
updatedAt: Date;
date: {
at: Date;
span: "day" | "weak" | "month";
field: "updatedAt" | "createdAt";
};
type: "conversation" | "message";
/**  _id => number of conversations/messages in the month */
distinct: "sessionId" | "userId" …
```
=> ✨ Add stats on conversations

src/routes/+layout.server.ts, src/routes/settings/+layout.server.ts
1. remove duplicated assistants query. Read[ this comment](https://github.com/huggingface/chat-ui/pull/859/files#r1497883349)
2. limit conversations to last 300 https://github.com/huggingface/chat-ui/pull/859/commits/c8624589fdc0d2921d3ba341c6167f498a6f66fa
=> [Mongo] optimizations

src/routes/+layout.server.ts
Follow up to https://github.com/huggingface/chat-ui/pull/859, specifically to [this comment](https://github.com/huggingface/chat-ui/pull/859#discussion_r1497978234)
Bug: when a user removes an assistant, the assistant was NOT being removed from the settings list.
[This PR fixes this problem](https://github.com/huggingface/chat-ui/pull/869#discussion_r1499470412)
=> [Assistants] Fix `remove` behaviour

src/lib/stores/settings.ts, src/routes/+layout.svelte, src/routes/assistant/[assistantId]/+page.svelte, src/routes/assistants/+page.svelte
* Add a settings button in start chat modal 
* Selecting an assistant you already are subscribed to skips the modal and goes directly to a new conversation
* Fix flicker delay when selecting model or assistant from `/models` and `/assistants`
=> Small UX updates assistants

src/lib/server/preprocessMessages.ts, src/routes/conversation/[id]/+server.ts
There was a bug where the websearch was fetching relevant chunks for context correctly but it wasn't getting injected into the prompt, this PR fixes that.
=> Pass websearch to `preprocessMessages`

package-lock.json, package.json, src/lib/types/Message.ts, src/lib/utils/tree/addChildren.ts, src/lib/utils/tree/addSibling.ts, src/lib/utils/tree/convertLegacyConversation.ts, src/lib/utils/tree/isMessageId.spec.ts, src/routes/conversation/+server.ts, src/routes/conversation/[id]/+page.svelte, vite.config.ts
Because `crypto.randomUUID()` is not available on non-secure contexts (for example `http` versions of chat-ui), this would break on non-https deployments of chat-ui.
This should fix #870 and fix #868
=> Use `uuid` for message ID generation instead of crypto method

README.md, package-lock.json, package.json, scripts/populate.ts
When testing changes I found myself often having to generate a bunch of data manually to get started testing. This PR adds a script that we can run to create users, assistants and conversations. 
You can populate the database using faker data using the `populate` script:
```bash
npm run populate <flags here>
```
At least one flag must be specified, the following flags are available:
- `reset` - resets the database
- `users` - populates the users table
- `settings` - populates the settings table for users in the db
- `assistants` - populates the assistants table for users in the db
- `conversations` - populates the conversations table for users in the db
> [!WARNING]  
> The `MONGODB_URL` used for this script will be fetched from `.env.local`. Make sure it's correct! The command runs …
=> Add a simple populate script

src/lib/components/chat/ChatMessage.svelte, src/lib/components/chat/ChatWindow.svelte, src/routes/conversation/[id]/+server.ts
* Show a "retry button" if something goes wrong
* Send an error if the endpoint terminates without streaming at least one token
* Fix the loading indicator that was spinning even if not loading
=> Improve error handling when posting new messages

src/lib/server/endpoints/llamacpp/endpointLlamacpp.ts
**Background**
Had this problem on 2 different setups, essentially the decoder for llamacpp would grab partially streamed json and decode it without the new line 
**Description**
Just wait until we see a new line character before trying to decode the json. if we fail to decode a token, just toss it. *may lead to tokens being thrown out but after a couple of days of running this thru the ringer it seemed to work, and dropping a word is a better UX than just crashing when it fails to decode the response
=> Bug Fix: Json Decoder aggessively pulls json

src/lib/server/endpoints/llamacpp/endpointLlamacpp.ts
We weren't properly indicating when the generation is done.
=> Fix issue with "continue" feature on llama.cpp endpoints

src/hooks.server.ts, src/lib/migrations/lock.ts, src/lib/migrations/migrations.spec.ts, src/lib/migrations/migrations.ts, src/lib/migrations/routines/01-update-search-assistants.ts, src/lib/migrations/routines/index.ts, src/lib/server/database.ts, src/lib/types/MigrationResult.ts, src/lib/types/Semaphore.ts
This PR adds a check on startup that runs migrations if needed.
Each migration is defined by it's. `_id`  field which is unique and hardcoded. When the migration is applied we add it to the `"migrationResults"` collections, so we can check if it has already been run. Each migration is wrapped in a transaction to ensure consistency.
The migration check runs at the top-level of `hooks.server.ts` to ensure it only runs once on startup.
Because we can have multiple instances of chat-ui running against a single DB we need to ensure we have a lock before running migrations. 
The code for lock related operations is under [lock.ts](https://github.com/huggingface/chat-ui/blob/f7fde32646f89ea31bcf461147e9f4da08f73c02/src/lib/migrations/lock.ts#L19) with the [associated …
=> Automated migration setup

src/routes/assistants/+page.svelte
As the user types on filter, the page should be set back to 0
=> [Assistants filter] Fix bug

src/lib/components/chat/ChatInput.svelte, src/lib/utils/isDesktop.ts, src/routes/assistants/+page.svelte
More UX fixes regarding assistants filter:
1. Don't call `input.focus` on mobile screens
2. Clear `input.value` when user changes model, or switches between {user}/comunity tabs
=> [Assisntans filter] More UX fixes

src/lib/server/sentenceSimilarity.ts
While working on RAG for assistants, I noticed that the last chunk was always missing from the websearch context. In my case it was quite important because my context only had one chunk 😆
=> Include last chunk in websearch context

README.md, src/lib/server/embeddingEndpoints/embeddingEndpoints.ts, src/lib/server/embeddingEndpoints/openai/embeddingEndpoints.ts, src/lib/server/embeddingModels.ts
This is working, but I haven't tested it extensively. I added a new optional parameter, maxBatchSize, which defaults to 100 if not set in the config. Apparently OpenAI's embedding endpoint can handle batches of 2048, but I also found reports of some users experiencing problems with large batches. 
It still needs a documentation update, and should probably be reworked to use the OpenAI library.
```
TEXT_EMBEDDING_MODELS = `[
{
"name": "text-embedding-3-small",
"displayName": "text-embedding-3-small",
"description": "OpenAI hosted embedding model",
"chunkCharLength": 768,
"endpoints": [
{
"type": "openai",
"url": "https://api.openai.com/v1/embeddings",
}
]
}
]`
```
=> Add openai embeddings

.env, README.md, package-lock.json, package.json, src/lib/server/endpoints/anthropic/endpointAnthropic.ts, src/lib/server/endpoints/endpoints.ts, src/lib/server/models.ts
Adds support for Anthropic via their official SDK and the newer [Messages API](https://docs.anthropic.com/claude/reference/messages-streaming). Left a todo regarding the `preprompt` which I passed to Anthropic via their `system` prompt option, rather than passing it in during `buildPrompt`. Let me know which would be preferable
https://github.com/huggingface/chat-ui/pull/923/files#diff-ef33885c5572e45b8c3ba8c5d6b489b258dc0a3fdd7bef12556481f71f5cd45fR53-R54
=> Anthropic Endpoint Support

src/lib/components/chat/ChatMessage.svelte
Apparently they are returned by the model so we can't really strip them at the source. I remove them in the renderer, which means the fix will also work for older conversations!
=> Remove extra > in URLs

src/routes/conversation/+server.ts
PR #181 introduced a model ID field so that models could be switched out without breaking existing conversations. However, the new conversation endpoint incorrectly uses the model name instead of ID, so without this fix it was not possible to have a model with a different ID and name.
=> Fix model identification when creating conversations

src/lib/utils/messageUpdates.ts, src/routes/conversation/[id]/+page.svelte
I noticed while using the Anthropic endpoint that the output would jump by ~10 tokens, pause for 200ms, and repeat. I've implemented [a smoothing function](https://github.com/huggingface/chat-ui/compare/main...superfishial:chat-ui:feat/smoothed-output?expand=1#diff-278e19521eb0ad173b98387709ab1c22e0b5cddf90aec08ba7a403db146bd845R147) for the streamed output that attempts to estimate the token/s and output at that rate instead.
I also added [a chunking function](https://github.com/huggingface/chat-ui/compare/main...superfishial:chat-ui:feat/smoothed-output?expand=1#diff-278e19521eb0ad173b98387709ab1c22e0b5cddf90aec08ba7a403db146bd845R105) that attempts to concatenate tokens like `do` and `n't`. It made it a bit easier to read, especially for long words and code which are split quite …
=> feat: smooth and combine token output

.env.template, src/lib/components/AssistantSettings.svelte, src/lib/components/TokensCounter.svelte, src/lib/server/models.ts, src/lib/types/Model.ts, src/routes/+layout.server.ts, src/routes/api/models/+server.ts, src/routes/settings/(nav)/[...model]/+page.svelte
On updating model settings:
<br><br>
On updating assitants settings:
=> Count system prompt tokens

src/routes/api/assistants/+server.ts, src/routes/api/user/assistants/+server.ts
Adding 2 endpoints to the API:
/api/assistants: A paginated endpoint to list/search across all assistants
/api/user/assistants: A endpoint to list current user's assistants and the ones he already used in the past
=> add api assistants endpoints

src/routes/login/callback/updateUser.ts
Currently it seems a user, when logging in for the first time, needs to
- sign up (with "sign in with HF")
- sign in
Because the sign up doesn't send the new cookie value to the user
=> 🚸 When a user signs up they're directly logged in

src/lib/server/preprocessMessages.ts, src/lib/server/websearch/runWebSearch.ts, src/lib/types/WebSearch.ts
Put the `context` text inside respective `contextSources` (suggested by @gary149 )
note: nothing is needed in terms of backward compatiblity. This change doesn't break anything from the old.
=> [Websearch] change context schema

src/lib/components/AssistantSettings.svelte, src/lib/components/TokensCounter.svelte, src/lib/components/chat/AssistantIntroduction.svelte, src/lib/types/Assistant.ts, src/routes/assistants/+page.svelte, src/routes/conversation/+server.ts, src/routes/conversation/[id]/+server.ts, src/routes/settings/(nav)/assistants/[assistantId]/+page.svelte, src/routes/settings/(nav)/assistants/[assistantId]/edit/+page.server.ts, src/routes/settings/(nav)/assistants/new/+page.server.ts, src/routes/settings/+layout.svelte
This PR takes over from #942 as it's more versatile and can be expanded with more features in the future.
The links are parsed as plain text directly. You can click on them directly to follow them.
The prompt in the example would give something like this
```
"<s> [INST]Your goal is to make the user guess a country. \r\n\r\nThe country of the day is: **American Samoa**\r\n\r\nAlso today is 3/21/2024 but you can also add spaces 3/21/2024\r\n\r\nAnd this is not a {{ valid tag }} so it doesn't get highlighted\r\n\r\n{{ really {{ really ?? }} }} [/INST]"
```
=> Dynamic system instructions

src/routes/api/conversations/+server.ts
We were missing the same limit that we use in the load function of the web app.
=> Limit number of fetched conversations in the API

src/lib/components/AssistantSettings.svelte, src/lib/components/HoverTooltip.svelte, src/lib/server/endpoints/anthropic/endpointAnthropic.ts, src/lib/server/endpoints/aws/endpointAws.ts, src/lib/server/endpoints/endpoints.ts, src/lib/server/endpoints/llamacpp/endpointLlamacpp.ts, src/lib/server/endpoints/ollama/endpointOllama.ts, src/lib/server/endpoints/openai/endpointOai.ts, src/lib/server/endpoints/tgi/endpointTgi.ts, src/lib/types/Assistant.ts, src/routes/conversation/[id]/+server.ts, src/routes/settings/(nav)/assistants/[assistantId]/edit/+page.server.ts, src/routes/settings/(nav)/assistants/new/+page.server.ts
| <img width="1186" alt="Screenshot 2024-03-27 at 13 31 03" src="https://github.com/huggingface/chat-ui/assets/25119303/f90846f1-70f5-4e49-a40e-5ab687b6a93c"> | <img width="324" alt="Screenshot 2024-03-27 at 13 29 59" src="https://github.com/huggingface/chat-ui/assets/25119303/a2793221-e5aa-4eaa-b82d-f2a7dde78e85"> |
| ------- | ------- | 
It opens by default if values are prefilled. I updated the endpoint code so it should work with every endpoint type. There's a tooltip for each field that works on mobile & desktop.
Had to deviate a bit from the design in #955, it was hard to fit the label and the field horizontally (only looked good on big screen at full width) so I ended up putting the label above the field. 
Also used the native html details/summary elements instead of a button, and …
=>  Expose sampling controls in assistants (#955) 

src/routes/assistants/+page.svelte
as written in the #938 [description](https://github.com/huggingface/chat-ui/pull/938#issue-2191919264), this PR is the last step for trending assistants
> Deployment plan
> 1. Get this PR approved
> 2. Hide the sort assistants UX/frontend while the data is being collected
> 3. Deploy
> 4. Enable/show sort assistants UX/frontend
=> [Trending assistants] make ui visible

README.md, package-lock.json, package.json, src/lib/server/endpoints/endpoints.ts, src/lib/server/endpoints/google/endpointVertex.ts, src/lib/server/models.ts
This commit adds support for the google cloud vertex API.   It relies on https://github.com/googleapis/nodejs-vertexai to connect.
To enable: 
1.  [Select](https://console.cloud.google.com/project) or [create](https://cloud.google.com/resource-manager/docs/creating-managing-projects#creating_a_project) a Google Cloud project.
1.  [Enable billing for your project](https://cloud.google.com/billing/docs/how-to/modify-project).
1.  [Enable the Vertex AI API](https://console.cloud.google.com/flows/enableapi?apiid=aiplatform.googleapis.com).
1.  [Set up authentication with a service account](https://cloud.google.com/docs/authentication/getting-started)
so you can access the API from your local workstation.
The service account credentials file can be imported as an environmental variable:
```env …
```
=> Google Vertex API support

src/lib/components/AssistantSettings.svelte
The buttons are currently floating in the div, this PR should fix it
=> Fix button placement on assistant edit/create form

src/routes/conversation/[id]/+server.ts
To avoid sending packets which have the exact size of the tokens, we group them together at random
=> Group tokens randomly

.env, README.md, src/lib/server/endpoints/cloudflare/endpointCloudflare.ts, src/lib/server/endpoints/endpoints.ts, src/lib/server/models.ts
This PR adds support for using Workers AI endpoints from Cloudflare. 
It's super easy and convenient to use. Specify `CLOUDFLARE_ACCOUNT_ID` and `CLOUDFLARE_API_TOKEN` in your `.env.local` then you can easily add any model in your `MODELS` var. (see readme changes to get those vars)
Here's a sample config with `nousresearch/hermes-2-pro-mistral-7b` :
```
MODELS=`[
{
"name" : "nousresearch/hermes-2-pro-mistral-7b",
"tokenizer": "nousresearch/hermes-2-pro-mistral-7b",
"parameters": {
"stop": ["<|im_end|>"]
},
"endpoints" : [
{
"type" : "cloudflare"
}
]
}
]`
```
Be mindful of the casing (different than on the hub) and it doesn't seem to support sampling parameters like temperature? 
Closes #907
=> Implement Cloudflare Workers AI endpoint (#907)

src/lib/server/models.ts
Wanted to make either chatprompttemplate or tokenizer mandatory, but since some endpoints type use chat completion/messages API, they don't need a chat template as it's handled by their backend.
This PR sets a default (ChatML), so that we won't throw an error when not setting the chat template. This reverts a breaking change.
https://github.com/huggingface/chat-ui/pull/744#issuecomment-2041644232
=> Set ChatML as default chat prompt template

src/routes/settings/(nav)/+page.svelte
The "on:close" event function is not triggered by the dispatch("close") before the page redirection (the modal is not properly removed and the page becomes unresponsive).
I removed the dispatch("close") and directly apply what is done by the "on:close" event function.
I tested it and now the page is responsive after deletion of all the conversations. It should fix #937
=> Fix unresponsive page after deleting all conversations

README.md, src/lib/server/endpoints/endpoints.ts, src/lib/server/endpoints/langserve/endpointLangserve.ts, src/lib/server/models.ts
Hey thanks for sharing chat-ui with the community! We have been using it for a while and would now like to contribute to continue making it great :)
LangServe is the go-to service for deploying LLM applications built using LangChain. Supporting this type of endpoint opens the door to using new Models in chat-ui that are powered up for example by using custom chains on top of an LLM.
Note, I am pretty new to Javascript so I am open to any feedback on the code !
=> Add langserve endpoint

src/lib/server/models.ts
We have an issue where the app will show a 500 error when it fails to load the tokenizer but won't properly crash. This is a temp fix, let's find a better solution later
=> Kill app on tokenizer load fail

.env, README.md, src/lib/server/auth.ts, src/routes/logout/+page.server.ts
We require a secure cookie for huggingchat, however some users might want to run `chat-ui` over http. While not recommended, we shouldn't be blocking users from doing so.
This PR adds `ALLOW_INSECURE_COOKIES` as an env variable which will allow insecure cookies if set to`ALLOW_INSECURE_COOKIES=true`.
Closes #877 
Closes #1057 
Closes #658 
Closes #364 
Closes #330 
This is a fairly common issue so I added a section in the readme about it.
=> Add `ALLOW_INSECURE_COOKIES` feature flag

src/lib/components/CopyToClipBoardBtn.svelte
Right now, the copy button is not easy to see it, I have put the same colour as the border to make it easier to see.
Now:
https://github.com/huggingface/chat-ui/assets/7398909/c98ab65e-02ec-4d15-80b1-7a9f01d4bfed
After:
https://github.com/huggingface/chat-ui/assets/7398909/dd65045d-a34b-4104-b330-8067e65c8377
=> 🎨 Add color for copy icon

src/lib/server/auth.ts, src/routes/logout/+page.server.ts
The `ALLOW_INSECURE_COOKIES` flag wasn't working properly since we had strict `sameSite` policy. 
Now when you `ALLOW_INSECURE_COOKIES=true` you get `secure:false` and `sameSIte: "lax"`
=> set `sameSite` to `lax` when allowing insecure cookies

.env.template
The chat template did not account for the begin-of-sentence token during conversations through HuggingChat. It plays an important role on Phi-3-mini-4k-instruct model and must be available for producing proper generations.
Example:
```
curl https://api-inference.huggingface.co/models/microsoft/Phi-3-mini-4k-instruct \
-X POST \
-d '{"inputs": "<s><|user|>\nHi<|end|>\n<|assistant|>\n"}' \
-H 'Content-Type: application/json'
```
*Without `<s>`, it starts producing unnecessary extra tokens.*
=> Adds <s> to Phi-3-mini-4k-instruct template configuration

package-lock.json, package.json, src/app.d.ts, src/hooks.server.ts, src/lib/assistantStats/refresh-assistants-counts.ts, src/lib/migrations/migrations.ts, src/lib/server/abortedGenerations.ts, src/lib/server/auth.ts, src/lib/server/database.ts, src/lib/server/embeddingEndpoints/hfApi/embeddingHfApi.ts, src/lib/server/embeddingEndpoints/tei/embeddingEndpoints.ts, src/lib/server/endpoints/cloudflare/endpointCloudflare.ts, src/lib/server/endpoints/langserve/endpointLangserve.ts, src/lib/server/endpoints/llamacpp/endpointLlamacpp.ts, src/lib/server/logger.ts, src/lib/server/models.ts, src/lib/server/preprocessMessages.ts, src/lib/server/summarize.ts, src/lib/server/websearch/searchSearxng.ts, src/routes/+error.svelte, src/routes/admin/export/+server.ts, src/routes/admin/stats/compute/+server.ts, src/routes/conversation/[id]/+server.ts, src/routes/settings/(nav)/assistants/[assistantId]/+page.server.ts
This PR adds `pino` for logs, which will give us JSON logging in prod and pretty logs in dev.
I also used this opportunity to [add a `handleError` hook](https://github.com/huggingface/chat-ui/pull/1086/files#diff-b5aa13ce0a61c3f166000471d0729aa6a8e57292fdbd8d88452443502e4b9a4aR33-R57). 
We now log extra info about the error's source and we also surface a unique `errorId` to the user which can be used for finding the error in the logs.
=> Use pino for logs

chart/env/prod.yaml
We are still trying to get to the root cause of the model de-railing after long conversations. We haven't been able to reproduce it locally (through scripts or chat-ui), so we are tackling some additional possibilities here.
=> Ensures more consistent hyperparameters to Phi-3-mini-4k-instruct

chart/env/prod.yaml
It was missing the temperature, which meant the retry feature wasn't working as expected.
=> Add temperature to Llama 3 70B on HuggingChat

src/routes/conversation/[id]/+server.ts
We shouldn't trim user inputs, as it can mess with tokenization if the user wants to do something specific.
And this also closes #1117
=> Remove trim on user input

src/lib/server/websearch/parseWeb.ts
When you combine assistant websearch with TEI, there was an error. (However, it was/is working fine with local models through transformers.js).
Although we have 
https://github.com/huggingface/chat-ui/blob/b2bee6290278fb70bba65fd2df8227508facc313/src/lib/server/embeddingEndpoints/tei/embeddingEndpoints.ts#L63, there was still an error (i.e. TEI endpoint was rejecting the input citing it as `invalid json`) when a text value was a text concat value (i.e. rather than `"Hello World"`, the actual value was `"Hello " + "World"`). Therefore, we needed to add https://github.com/huggingface/chat-ui/blob/b2bee6290278fb70bba65fd2df8227508facc313/src/lib/server/websearch/parseWeb.ts#L35-L37
=> [fix] Assistant websearch text/markdown source

chart/env/prod.yaml
=> Add 01-ai/Yi-1.5-34B-Chat

chart/env/prod.yaml
Sorry for sending a bunch of PRs on the same matter 😄 
We decided to set `temperature=0.0` to have a more controlled environment and attempt to fix the issue for real. One thing that we were thinking and I don't know the answer is the following:
When the truncation happen, it is done in the `left` or `right` side of the context? Is there a way to set it? I looked on the https://github.com/huggingface/chat-ui/blob/main/src/lib/server/models.ts file, but it could be somewhere else.
Thanks and best regards,
Gustavo.
=> Uses temperature 0.0 for Phi-3.

src/lib/server/websearch/scrape/playwright.ts
Fixes an issue where the playwright context will remain closed because we don't attempt to recreate it after it closes. This solves it by clearing the singleton on close.
=> Clear playwright singleton on close

src/lib/migrations/routines/04-update-message-updates.ts
Fixes the message update migrations needed as part of #996 not applying to the tools objects.
=> Fix message update migration not applying

README.md
Existing README.md instructions for setting up the OpenAI compatible server do not pass extra parameters correctly. To resolve this, we have made changes through PR #1032. The README.md has been updated to reflect these modifications.
=> Update documentation of OpenAI compatible server configuration

chart/templates/deployment.yaml, chart/templates/ingress.yaml, chart/values.yaml
This PR adds a bit of flexibility to facilitate the use of the chart by the community:
* Allow to disable ingress
* Allow to specify the tls block in the ingress
* Allow to specify the ingress classname
* Allow to pass extra env variable (via env or envFrom)
=> Improve helm chart

src/lib/server/auth.ts, src/routes/login/callback/+page.server.ts
This PR fixes a bug where `chat-ui` does not parse the `iss` if the OIDC provider returns it in the `url` (for example, when using `keycloak>23`). 
Let me know if you would like me to open an issue for this as well.
1. optional parse of `iss` from `url.searchParams.entries()`
2. updated `getOIDCUserData` to pass the `iss`
Tests:
1. [x] `npm run test`
2. [x] tested with a OIDC provider that does not return `iss` (previous behavior is maintained, as `iss` is undefined, the same if condition from the `openid-client` library is evaluated.)
3. [x] tested with a OIDC provider that returns `iss` and working
=> fix: parse ISS if returned in OIDC flow

src/lib/server/websearch/scrape/playwright.ts, src/lib/server/websearch/scrape/scrape.ts
Supersedes #1184. What I would do for a `with:` api in TS...
Switches to using a single context per page and making only the browser consistent. Creates the blocker on init since it's too slow to run for every new context, but doesn't need to be recreated, like the browser, on failure. Adds a `withPage` api so that consumers of the playwright don't need to worry about leaking memory.
=> Fix Playwright leak and use multiple contexts

src/lib/migrations/routines/04-update-message-updates.ts, src/lib/migrations/routines/06-trim-message-updates.ts, src/lib/migrations/routines/index.ts, src/lib/server/websearch/runWebSearch.ts, src/lib/server/websearch/update.ts, src/lib/types/MessageUpdate.ts, src/routes/conversation/[id]/+server.ts
The websearch was returning updates which contained a lot of information we don't use in the front-end. 
This PR removes the data from the DB and remove the unnecessary data from websearch updates.
=> Reduce message update size returned by websearch

src/lib/server/textGeneration/tools.ts, src/lib/server/tools/calculator.ts, src/lib/server/tools/directlyAnswer.ts, src/lib/server/tools/documentParser.ts, src/lib/server/tools/images/editing.ts, src/lib/server/tools/images/generation.ts, src/lib/server/tools/index.ts, src/lib/server/tools/web/search.ts, src/lib/server/tools/web/url.ts, src/lib/utils/stringifyError.ts
Continues #1163 by having tools simplify throw errors rather than returning an explicit error or success status. Also introduced a util for stringifying unknown errors so we'll hopefully find less `[Object object]` errors downstream from libraries which don't use the native `Error` object
=> Simplify tool error handling

src/lib/server/textGeneration/tools.ts
[slack context](https://huggingface.slack.com/archives/C06U2V0L0LB/p1716888678428789?thread_ts=1716884604.014799&cid=C06U2V0L0LB)
follow up to https://github.com/huggingface/chat-ui/pull/1168
When tool fails, a generic error msg "Error occurred" will be shown rather than the actual error msg for various reasons, including security concerns as it may reveal information that is not intended to the user. However, the actual error will still be logged for debugging (for admins)
=> Generic tool error msg "Error occurred"

src/lib/types/User.ts, src/routes/+layout.server.ts, src/routes/settings/(nav)/assistants/[assistantId]/+page.server.ts, src/routes/settings/(nav)/assistants/[assistantId]/+page.svelte
Only lets you unfeature/delete assistants for now.
Was needed because deleting assistants requires deleting it from every user's settings which was impossible to do manually
Currently admins are created by setting `isAdmin` manually on the user document in the DB
=> Add super basic admin feature

.env, README.md, docs/source/configuration/web-search.md, src/lib/server/websearch/search/endpoints.ts, src/lib/server/websearch/search/endpoints/searchApi.ts, src/routes/+layout.server.ts
We have integrated a new webSearch - [SearchApi](https://www.searchapi.io/), following a similar format to the other SERP providers.
- Feel free to assign @SebastjanPrachovskij as a main reviewer for any SearchApi-related searches. We will be glad to help and support chat-ui development.
=> Add support for SearchApi API

src/lib/components/AssistantSettings.svelte
Multiple problems with how it was before:
- There was no need to use a gendered pronoun in the first place
- I don't think we've gotten to the point where we can refer to machine learning models with human pronouns
Another possibility if you want to use human pronouns is “they.”
=> Remove gendered pronoun

src/lib/components/chat/ChatWindow.svelte, src/lib/components/chat/FileDropzone.svelte
Since #1204 adds MIME types, I extended their use to the `onPaste` handler as well as the `FileDropzone` component
=> Only paste or drop the allowed MIME types

docs/source/configuration/models/tools.md, docs/source/configuration/web-search.md, docs/source/index.md
1. Interlink pages
2. Add images
=> Improve docs

src/lib/components/ToolsMenu.svelte, src/lib/components/UploadBtn.svelte, src/lib/components/chat/ChatWindow.svelte, src/lib/components/chat/FileDropzone.svelte, src/lib/server/tools/documentParser.ts, src/lib/server/tools/images/editing.ts, src/lib/types/Tool.ts, src/routes/+layout.server.ts
Adds a mimetypes property on the tools used by the frontend to control the `UploadBtn`'s `accept` property. If there are no active mime types, the upload button will not be shown. Adds an enable/disable all button to the tools menu
=> feat: mime types on tools, show upload btn on demand

src/lib/server/endpoints/ollama/endpointOllama.ts
Before you had to `ollama pull [whatevermodel]` manually in ollama. I wanted a single deployment with ollama+chat-ui where I didn't have to run any commands. 
This PR handles the downloading of the model directly from the endpoint if needed.
=> Send `ollama pull` request if model is not available locally

src/lib/server/textGeneration/tools.ts
The model likes to return trailing commas on the tool calls which JSON5 rejects. This trims the comma and adds a clearer message for the client for when tool call parsing fails
=> Trim trailing comma on tool calls

src/lib/migrations/routines/03-add-tools-in-settings.ts, src/lib/server/database.ts, src/lib/server/embeddingEndpoints/hfApi/embeddingHfApi.ts, src/lib/server/endpoints/cloudflare/endpointCloudflare.ts, src/lib/server/endpoints/langserve/endpointLangserve.ts, src/lib/server/endpoints/llamacpp/endpointLlamacpp.ts, src/lib/server/websearch/search/endpoints/searxng.ts
Logging for chat-ui was switched to Pino in https://github.com/huggingface/chat-ui/pull/1086. For error logging, Pino wants the object first, and then the string message. Otherwise you don't get the information from the error object. For example see this thread: https://github.com/pinojs/pino/issues/673
There's already one example in the repo of correct usage: https://github.com/huggingface/chat-ui/blob/main/src/lib/server/textGeneration/tools.ts#L95
=> Fix error logging

README.md, src/lib/server/endpoints/google/endpointVertex.ts
The googleSearchRetrieval leads to very odd and unnatural behavior when chatting with Gemini. Making the argument optional and removing it for certain use cases fixes the issue. 
Behavior with googleSearchRetrieval:
=> Fix: tools in endpointVertex now optional

package.json
The script itself and the documentation about it were deleted in https://github.com/huggingface/chat-ui/pull/1107 already.
- Script `updateProdEnv` from `package.json`
=> Npm: Remove updateProdEnv from script from package.json

src/lib/server/textGeneration/index.ts
the check to see if we needed to run websearch would not run it if the model had tools
but it should run it if the request comes from an assistant since we ignore tools for assistants for now
=> fix websearch on assistants

src/lib/server/websearch/scrape/playwright.ts
Closes #1242
Closes #1247 
In environment without access to github, building the playwright blocker would fail, causing the app to crash
=> Handle errors gracefully in building PlaywrightBlocker

src/lib/utils/messageUpdates.ts, src/routes/conversation/[id]/+server.ts
We were running into issues with the file upload mechanism. The old way was to encode the file as a `base64` string and POST a request with a JSON body, including the files. This worked OK locally but the body got too big in prod and the request would get denied with a 413. 
So I switched to using `FormData` instead (like we do for the assistant avatar since that seemed to work ok).
In order to keep the PR simple, everything except the files is still a stringified JSON inside of `form.get('data')` but I moved the files to `form.getAll("files")`
=> Fix max upload size in huggingchat

src/lib/server/websearch/scrape/parser.ts
Fix of the error that occurs during parsing of the web search results
=> fix(scrape parser): Cannot read properties of 'undefined' during page parsing

src/lib/components/chat/ChatWindow.svelte
Closes: https://github.com/huggingface/chat-ui/issues/1113
=> fix(screen-reader): disable FileDropZone area-label for models without file upload

src/lib/server/endpoints/llamacpp/endpointLlamacpp.ts
llamacpp endpoint was using an `url` param instead of `baseURL` like everyone else
=> Standardize llama.cpp endpoint with `baseURL`

.env, src/lib/server/textGeneration/title.ts
Closes: https://github.com/huggingface/chat-ui/issues/1289 😅
=> fix(env): change env var typo

src/lib/components/DisclaimerModal.svelte, src/lib/components/LoginModal.svelte
Closes: https://github.com/huggingface/chat-ui/issues/1314
=> Fix "login" button text wrap on mobile

chart/env/prod.yaml
- adds more replicas as a temporary measure to mitigate against crashes
- reduces cpu and mem requests to what we've observed in practice over the last week
=> perf: add prod deployment resources

src/lib/components/NavConversationItem.svelte, src/lib/components/NavMenu.svelte, src/lib/components/chat/ChatWindow.svelte, src/lib/components/chat/FileDropzone.svelte, src/routes/assistant/[assistantId]/+page.svelte
Dropzone shows when you drag on window
=> UX: Dropzone

src/lib/server/endpoints/cloudflare/endpointCloudflare.ts
Add support for `@cf/models` and ensure compatibility with models without `@hf/`. Fixes #1364
=> Add support to @cf models with cloudflare.com

README.md
ref: https://x.com/dnouri/status/1821197502760030686?s=46
=> Add steps to install from source for llama.cpp

src/lib/components/CodeBlock.svelte, src/lib/components/CopyToClipBoardBtn.svelte, src/lib/components/chat/ChatMessage.svelte
Fix to copy button styling identified in Issue #1387 . Copy button under "ChatMessage" now consistent with other Icons. The component is also used as an icon in "CodeBlock.svelte". The styling for CodeBlock has been kept as it was.
PR recreated due to user error.
=> Fix "Copy" button styling. Relates to issue 1387 

.env, src/lib/server/websearch/scrape/playwright.ts
This change makes the playwright websearch timeout value configurable through an environment variable. The default value is set to 3500 ms.
=> Configurable websearch timeout

src/lib/buildPrompt.ts, src/lib/server/models.ts, src/lib/types/Template.ts
Made the end token stripping code more robust
Also made sure to set `add_generation_prompt: false` for continue mode
Paired with fixes to the chat prompt template for llama 3.1 70b: https://huggingface.co/nsarrazin/llama3.1-tokenizer/commit/9bf7a8ffd049a7f43d6c93b327cc5ab7f0e17c4b
should fix continue mode
=> fix(continue): fix continue feature 

src/lib/server/tools/index.ts
since tools are often represented as python function in the prompt, some models had trouble calling functions with names that had spaces in them for example
=> fix(tools): tool call name must be a valid python variable name

src/lib/server/textGeneration/index.ts, src/routes/conversation/[id]/+page.svelte
This should fix the web search toggle for llama 3.1 and command R+ on the native apps.
We were setting the toggle to false on all requests where the model had tools but since the native apps don't have tool support yet this would prevent it from working
=> fix(websearch): fix `webSearch` flag use for model with tool use

src/routes/models/+page.svelte
blue icon to differentiate multimodal models on the `/models` page (see bottom one)
=> feat(front): add multimodal icon on model page

src/lib/server/endpoints/cohere/endpointCohere.ts
This pull request addresses the issue described in https://github.com/huggingface/chat-ui/issues/1404#issue-2460503883, where attempting to use tools with the Cohere endpoint results in the following error: `cannot specify both message and tool_results in multistep mode`.
Since the Chat UI project handles the tool usage process, the multistep feature provided by the Cohere endpoint is unnecessary in this context. Therefore, I've modified the implementation to enforce a single API call, which resolves the issue.
**Tested on:**
- **OS**: Ubuntu 22.04 
- **Node.js Version**: v22.9.0
=> Fix: Cohere Endpoint - Add Support for Tools

src/lib/components/chat/ChatInput.svelte
Fix [#1471](https://github.com/huggingface/chat-ui/issues/1471) for mobile users to add a new line to their messages.
=> Added enter to insert new line on mobile instead of default.

src/lib/components/chat/ChatWindow.svelte, src/routes/assistants/+page.svelte, src/routes/models/+page.svelte, src/routes/tools/+page.svelte
Here's a basic pull request for an attempt at fixing #1492
You can use it as a starting point. It's not tested (tried to run `npm run preview` locally but it failed due to lack of MongoDB, seems like getting this to work isn't trivial for me and it'd take some more time and effort than I have right now).
I simply removed the tailwind class `mr-1`, which means:
```css
.mr-1 {
margin-right: .25rem;
}
```
From instances of `custom-scrollbar` in these source files:
`src/lib/components/chat/ChatWindow.svelte`
`src/routes/assistants/+page.svelte`
`src/routes/models/+page.svelte`
`src/routes/tools/+page.svelte`
You'll need to test it yourself to ensure it actually works.
=> Remove right margin from custom scrollbar

scripts/populate.ts, src/lib/migrations/routines/06-trim-message-updates.ts, src/lib/migrations/routines/07-reset-tools-in-settings.ts, src/lib/migrations/routines/08-update-featured-to-review.ts, src/lib/migrations/routines/index.ts, src/lib/server/database.ts, src/lib/server/sendSlack.ts, src/lib/types/Assistant.ts, src/lib/types/Review.ts, src/lib/types/Tool.ts, src/routes/+layout.server.ts, src/routes/api/assistants/+server.ts, src/routes/api/tools/[toolId]/+server.ts, src/routes/api/tools/search/+server.ts, src/routes/assistants/+page.server.ts, src/routes/assistants/+page.svelte, src/routes/settings/(nav)/assistants/[assistantId]/+page.server.ts, src/routes/settings/(nav)/assistants/[assistantId]/+page.svelte, src/routes/settings/(nav)/assistants/new/+page.server.ts, src/routes/tools/+page.server.ts, src/routes/tools/+page.svelte, src/routes/tools/[toolId]/+layout.server.ts, src/routes/tools/[toolId]/+page.server.ts, src/routes/tools/[toolId]/+page.svelte, src/routes/tools/new/+page.server.ts
Currently we review all tools & assistants without checking if the user wants it to be reviewed. This means that we waste a lot of time on private stuff, tools that don't work, etc.
With this, the user can now ask to be featured, which will set a flag on the assistant and trigger a slack notification. Then the admin has two buttons to approve or deny a request. Once a request is denied the user won't be able to retrigger the flow. Admins can at any time reset an assistant or a tool to private (to un-feature something).
[(slack link)](https://huggingface.slack.com/archives/C052EKHD1U0/p1728468364907289?thread_ts=1728464686.106719&cid=C052EKHD1U0)
The  `featured: boolean` flag was replaced by `review: "PRIVATE"|"PENDING"|"APPROVED"|"DENIED"`, with the appropriate migrations for tools & …
=> feat: Update featured workflow to allow user to submit featured requests

src/lib/components/chat/ChatWindow.svelte, src/lib/server/endpoints/document.ts, src/lib/server/endpoints/google/endpointVertex.ts, src/lib/server/models.ts, src/lib/types/Model.ts, src/routes/+layout.server.ts
Following this issue https://github.com/huggingface/chat-ui/issues/1505, adding PDF and plain text support to Vertex.
The basis has also been setup for other endpoints that would support inline documents.
**DEMO**
https://github.com/user-attachments/assets/a417bfbb-7212-439f-a562-1f984544ff69
=> [vertex] Add PDF/plein texts support

src/lib/components/Modal.svelte
Quite often, my whole interface freezes after I close the modal, but with tools, it happens to me every time.
It seems like Svelte's issue with animation: https://github.com/sveltejs/kit/issues/5434
Steps to reproduce:
- click 'globe' icon in tools
- close modal
- interface will freeze
https://github.com/user-attachments/assets/f717687a-2f45-4c17-a057-9f6df73ec793
=> fix(modal): fix freeze after modal close

src/lib/components/chat/ChatMessage.svelte, src/lib/server/endpoints/endpoints.ts, src/lib/server/endpoints/google/endpointVertex.ts, src/lib/server/textGeneration/generate.ts, src/lib/types/MessageUpdate.ts
Some endpoints like VertexUI provides web sources used to generate the message.
This PR add the basis for any endpoint to add sources. They just have to provide `webSource` in the endpoint `output`.
Vertex implementation is done as an example.
https://github.com/user-attachments/assets/93dc4a26-fc08-45e5-96dc-a47a1e4eda43
=> [feat] Add support for endpoint web sources

src/lib/components/NavConversationItem.svelte
This PR improves the user experience of the conversation deletion flow by swapping the positions of the confirm and cancel buttons. After clicking the delete icon, the confirm (checkmark) button now appears closer to the original click position, reducing unnecessary mouse movement.
- Reordered confirmation buttons in `NavConversationItem.svelte`
- Confirm button (✓) now appears first, followed by cancel button (×)
- Maintained all existing functionality including shift+click shortcut
- No changes to the underlying delete logic
Fixes #1546
=> fix(ui): swap delete confirmation buttons for better UX (#1546)

src/hooks.server.ts, src/lib/server/models.ts
Closes #1432 
Some models don't support system prompts, therefore, a new `modelConfig` option has been added: `systemRoleSupported `
By default, the `systemRoleSupported ` option is `true`, where everything behaves as is. However, if the `systemRoleSupported ` option is set to `false`, all `role: "system"` messages are filtered out. And the very first `role: "system"` message encountered, will have its content preprended to the very first user message.
Brief example, let's assume the following is our `messages` array, before processing:
```json
[
{ "content": "Welcome to our service!", "role": "system" },
{ "content": "Hi, how can I help you today?", "role": "system" },
{ "content": "I need help with my account.", "role": "user" },
{ "content": "Certainly! What issue are you …
```
=> feat: Add a model config option to disable system prompts

src/lib/components/chat/ChatMessage.svelte, src/lib/components/chat/ChatWindow.svelte, src/lib/components/chat/UploadedFile.svelte, src/lib/server/endpoints/preprocessMessages.ts
https://github.com/user-attachments/assets/66cff008-a8e9-4565-b162-e34e5d10934f
Pretty simple, if we detect a paste event with more than 256 characters, we prevent the paste and instead create a new plaintext file. 
We also add preprocessing code to inject plain text files directly into the prompt and a little modal to display the plaintext content.
We use a custom MIME type `application/vnd.chatui.clipboard`  to differentiate between uploaded plaintext files and clipboard content
=> feat: paste long context as plaintext files

src/lib/components/MobileNav.svelte, src/lib/components/NavConversationItem.svelte, src/lib/components/NavMenu.svelte, src/lib/types/ConvSidebar.ts, src/routes/+layout.server.ts, src/routes/+layout.svelte, src/routes/conversation/[id]/+page.svelte, src/routes/settings/(nav)/assistants/[assistantId]/+page.svelte, src/routes/settings/+layout.server.ts
Will help reduce loading times by streaming the conversations instead of blocking page load until they are fetched.
also cuts initial SSR transferred bytes by 50% when the user has 300 conversations or more
=> feat: lazy stream conversations load function

src/lib/components/chat/ChatMessage.svelte
For sources display, we use Google API (for instance `https://www.google.com/s2/favicons?sz=64&domain_url=github.com`). But when for some reason the hostname (`new URL(link).hostname`) is not well computed, we end up with a broken link `https://www.google.com/s2/favicons?sz=64&domain_url=` and the icon is replaced by the `alt` attributes, which can lead to very weird display:
So this fix sets the hostname to `placeholder` when not well computed `https://www.google.com/s2/favicons?sz=64&domain_url=placeholder`
=> [fix] Add placeholder param for sources icon

docs/source/configuration/embeddings.md
Added an example on how to use OpenAI API embedding models to the documentation.
=> Added example for OpenAI API embedding models

README.md
This PR fixes errors that occur if you try to follow the "Local setup" section of the `README.md`.
1. Move `.env.local` to the `chat-ui` directory
The first change is that the `.env.local` file needs to be inside the `chat-ui` directory, so I have moved the creation commands to where the user has already `cd`-ed into the directory.
2. Fix tokenizer name
The second change (line 68 -> 83) fixes the startup error:
```
ERROR (89579): Failed to load tokenizer microsoft/Phi-3-mini-4k-instruct-gguf make sure the model is available on the hub and you have access to any gated models.
err: {
"type": "Error",
"message": "Could not locate file: \"https://huggingface.co/microsoft/Phi-3-mini-4k-instruct-gguf/resolve/main/tokenizer_config.json\".",
"stack":
Error: Could not locate file: …
```
=> fix local setup instructions in README.md

src/hooks.server.ts
refreshSessionCookie() is called twice for POST requests. 
Removed the call which sends the _server_ id to the client.
=> fix: double cookie refresh in server hooks

chart/env/prod.yaml
Removing unneeded QwQ System prompt as HF Inference API automatically adds the default system prompt as defined in [chat_template](https://huggingface.co/Qwen/QwQ-32B-Preview/blob/main/tokenizer_config.json#L197)
=> Remove unneeded QwQ System prompt

docs/source/configuration/models/providers/openai.md, src/lib/components/chat/MarkdownRenderer.svelte, src/lib/server/endpoints/openai/endpointOai.ts
1. Fixing a bug with `systemRoleSupported` for the OpenAI endpoint. 
2. Now using `max_completion_tokens` over `max_tokens` when querying `chat_completions` endpoint.
The bugfix is necessary as `o1-preview` and `o1-mini` models do not support "system" message types.
The token configuration change was necessary as `o1-preview` and `o1-mini` no longer support the, _now deprecated_, `max_tokens` field.
I added a new endpoint configuration field called `useCompletionTokens` and defaulted it to `true`. 
This would have the effect of changing the default `chat_completions` call to use `max_completion_tokens` over `max_tokens`.
There may be unintended consequences for users, as this could increase their overall token usage per query (as the default would change). 
It may be prudent to start with …
=> feat(openai): added support for o1 reasoning models

chart/env/prod.yaml, src/lib/components/chat/ChatWindow.svelte, src/lib/stores/loginModal.ts, src/routes/+layout.svelte, src/routes/assistants/+page.svelte, src/routes/tools/+page.svelte
before it would just fail silently when you tried creating a tool or assistant without being logged-in so this tells users they have to login
=> feat: show login modal if login is required for creating assistants & tools

src/lib/components/chat/MarkdownRenderer.svelte
This update introduces KaTeX support for rendering block and inline math expressions within Markdown content. The changes include new tokenizer and renderer extensions for handling KaTeX syntax.
This update will fix #1599 and any other issues related to LaTeX or Markdown parsing.
- Added `katexBlockExtension` and `katexInlineExtension` for KaTeX block and inline math rendering.
- Removed the `escapeHTML` and `processLatex` functions.
- Updated the marked configuration to include the new KaTeX extensions.
- Modified `MarkdownRenderer.svelte` to import and use the new extensions.
=> feat: add KaTeX support for block and inline math rendering in Markdown

src/lib/components/AssistantSettings.svelte, src/lib/server/textGeneration/assistant.ts, src/routes/settings/(nav)/assistants/[assistantId]/+page.svelte
Allow the use of {{currentDate}} in an assistant Dynamic Prompt, which inserts the date in the format "Tuesday, 14 January 2025".
Not sure if anyone else wants this? - and implementation could probably be more robust (e.g. able to use from normal system prompts, not require ASSISTANT_RAG). Happy to take guidance on improving implementation.
=> Added currentDate variable to Dynamic Prompt

.env, src/routes/login/callback/+page.server.ts
e.g.
ALLOWED_USER_DOMAINS=`["example.com"]`
will allow both foo@example.com and bar@example.com
A user can log in if one of the conditions is true:
- ALLOWED_USER_DOMAINS and ALLOWED_USER_EMAILS are empty
- their email is in ALLOWED_USER_EMAILS
- their email domain ALLOWED_USER_DOMAINS
Fixes #1650
=> Add support for allowing users based on their domain

src/lib/components/chat/ChatMessage.svelte, src/lib/components/chat/ChatWindow.svelte
Removes the unused `model` prop from `ChatMessage`. Please let me know if it is correct
=> Rm unused prop

src/lib/components/chat/ChatMessage.svelte
var `downloadLink` seem to be always defined
hide the whitespace diff
=> Rm redundant if check

src/lib/server/endpoints/aws/endpointBedrock.ts
#1629 accidentally broke non-Nova models, fixes the incorrect parameter
=> fix: bedrock prepareMessages parameters

src/lib/components/ScrollToBottomBtn.svelte
Hi @nsarrazin!
I'm trying to refactor this component with the most minimalist way possible!
I hope the CI will be good too :crossed_fingers: 
Following https://github.com/huggingface/chat-ui/issues/1691
=> refactor: migrating ScrollToBottomBtn to svelte-5

src/lib/server/textGeneration/generate.ts
moving final answer outside of reasoning block so the ui displays all tokens for non reasoning models
=> fix: move FinalAnswer outside of reasoning processing blocks

src/lib/components/chat/ChatWindow.svelte
use a reverse column layout so that the default scroll position is at the bottom on ssr, which removes the annoying flash when reloading the page
=> feat(front): autoscroll at bottom on ssr

chart/env/prod.yaml, src/lib/server/textGeneration/reasoning.ts, src/lib/server/textGeneration/title.ts, src/lib/server/textGeneration/tools.ts, src/lib/server/tools/getToolOutput.ts, src/lib/server/websearch/search/generateQuery.ts
For the following tasks:
* web query generation
* summary of titles
* summary of reasoning steps
we now use tool calling if its available on the task model, with a single tool. 
(On HuggingChat the task model is llama 3.1 8B which can do tool calling so we enable it)
The intuition here is that the smaller model will be less confused with strict tool definitions and this should reduce answers that start with "Sorry but..." or irrelevant answers such as [this](https://huggingface.co/spaces/huggingchat/chat-ui/discussions/372#67cab5133a6e3e8656d28ffc).
=> feat(tasks): use tools for tasks if available

src/lib/server/endpoints/openai/endpointOai.ts, src/lib/server/endpoints/openai/openAIChatToTextGenerationStream.ts, src/lib/types/Tool.ts
Add Tool id to Open ai tools calls.
Allows tools to work, especially for the Mistral AI api, via the open ai library.
=> Add `toolId` to ToolCall and use it in tool results

src/lib/components/chat/ChatWindow.svelte
In Svelte 5, actions only update when the bound value changes by reference. Previously, snapScrollToBottom was bound to `messages`, which didn't trigger updates when only the content of a message changed during streaming.
Updated binding to `messages.map(message => message.content)` to ensure the action reacts to content changes, restoring expected scroll behavior.
Fix #1766
=> Fix auto-scroll issue with message streaming in Svelte 5

src/lib/server/models.ts
This feature lets you simplify your `MODELS` env var by just specifying a bunch of model names on the hub and letting chat-ui deal with the rest.
For example
```
MODELS=['HuggingFaceTB/SmolLM2-1.7B-Instruct-GGUF']
```
would automatically download the relevant file and serve it locally with `node-llama-cpp`
The goal of this is to keep simplifying the setup experience of chat-ui for most users. #1774
=> feat: allow strings in `MODELS` env var

Dockerfile, package-lock.json, package.json
This PR fixes #1812 and fixed #1811. It essentially:
- Updates `playwright` to `1.52.0` in `Dockerfile`
- And updates `playwright-chromium` to `1.52` in package.json and the lockfile.
I've hit the same problems as @wayubi and others, and had same error output, i.e:
```
{"level":50,"time":1746226913038,"pid":30,"hostname":"e0ec72572b93","err":{"type":"Error","message":"browserType.launch: Executable doesn't exist at /home/user/.cache/ms-playwright/chromium_headless_shell-1169/chrome-linux/headless_shell\n╔═════════════════════════════════════════════════════════════════════════╗\n║ Looks like Playwright Test or Playwright was just installed or updated. ║\n║ Please run the following command to download new browsers:              ║\n║ …
```
=> fix: use playwright-chromium@1.52.0 to fix scraping errors

src/lib/components/chat/ChatInput.svelte
The UI erroneously detects a touchscreen laptop as a phone and assumes it has a virtual keyboard, which makes the Enter button not send a message but rather start a new line. This was mentioned in #1767.
=> Fix incorrect touchscreen detection

src/lib/components/chat/MarkdownRenderer.svelte, src/lib/utils/updates.ts, src/routes/conversation/[id]/+page.svelte
This seems to help a lot when testing with CPU throttling in chrome dev tools. This was an issue for a lot of people and it got worse the longer the message got. Long-ish response were not working well on mobile, before.
With this PR we debounce changes for rendering, so the message is rendered less frequently based on how long it takes to parse + sanitize the markdown content into renderable HTML. 
This could be improved further with fading in or some kind of animation to hide the debounce but I don't think it's worth it for now.
=> refactor: improve rendering performance on low-end hardware

src/lib/server/websearch/search/generateQuery.ts
Remove quotes from search query to prevent exact match search. This issue only happens when running locally.
=> fix: remove quotes from search query to prevent exact match search

src/lib/server/generateFromDefaultEndpoint.ts
- Refactor error handling in the generateFromDefaultEndpoint function to prevent the Node.js process from crashing when an AbortError occurs.
- Wrapped the getEndpoint and endpoint calls within a try...catch block to ensure that exceptions are caught and the process remains stable.
```
AbortError: This operation was aborted
at node:internal/deps/undici/undici:13510:13
at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
at async file:///app/build/server/chunks/models-BZWchM1f.js:9918:17
at async generateFromDefaultEndpoint (file:///app/build/server/chunks/_server.ts-DQzfZKIq.js:380:23)\n    at async getReturnFromGenerator (file:///app/build/server/chunks/_server.ts-DQzfZKIq.js:405:14)
at async generateTitle …
```
=> fix: Improve error handling in generateFromDefaultEndpoint

.env, src/app.d.ts, src/hooks.server.ts, src/lib/server/apiToken.ts, src/lib/server/auth.ts, src/lib/server/config.ts, src/lib/server/endpoints/endpoints.ts, src/lib/server/generateFromDefaultEndpoint.ts, src/lib/server/models.ts, src/lib/server/router/arch.ts, src/lib/server/router/endpoint.ts, src/lib/server/textGeneration/generate.ts, src/lib/server/textGeneration/index.ts, src/lib/server/textGeneration/reasoning.ts, src/lib/server/textGeneration/title.ts, src/lib/server/textGeneration/types.ts, src/lib/types/Session.ts, src/routes/conversation/[id]/+server.ts, src/routes/login/callback/+server.ts, src/routes/login/callback/updateUser.spec.ts, src/routes/login/callback/updateUser.ts
Need `USE_USER_TOKEN="true"` in env to sue the user token
Still need to:
- refresh oauth token when it expires
- otherwise force oauth login to always have a oauth fresh token
and, separate:
- automatically login via oauth if a param is set
cc @gary149
=> Store oauth token in DB + use it when doing API calls

.env, src/hooks.server.ts, src/lib/server/adminToken.ts, src/lib/server/auth.ts, src/lib/server/endpoints/openai/endpointOai.ts, src/routes/login/+server.ts
Env to test things:
```
#.env.local
OPENID_CLIENT_ID=8f1a1d63-479b-46c8-84cb-521fe9f3222f
OPENID_CLIENT_SECRET=...
OPENID_SCOPES="openid profile inference-api"
USE_USER_TOKEN=true
AUTOMATIC_LOGIN=true
```
This PR forces a login when user is not logged in. We could tweak it that on failure, for the same session, it doesn't retry (currently it always retries)
We can also add a "prompt=none" in the oauth param (via another env var) and tweak the backend to automatically authorize the oauth app, if we want something 100% seamless. Currently the consent screen shows.
Still need to:
-   refresh oauth token when it expires
-   otherwise force oauth login to always have a oauth fresh token
=> Automatic login
